# -*- coding: utf-8 -*-
"""Batch 1: Rows 509 to 700 (192 lines)"""

batch1_data = {
    509: 'Ha ha ha!',
    510: 'Thực ra thanh kiếm này chỉ để làm cảnh thôi!',
    511: 'Mà này, ta chưa từng thấy ai trong các người\nở quanh đây bao giờ...',
    512: 'Tôi là <NAME=CP_0002>...',
    513: 'Đây là <NAME=CP_0001>, còn đây là <NAME=CP_0003>.',
    514: 'Chúng tôi đến từ <NAME=MA_0003_01>.',
    515: 'Đảo Nive... Ra vậy à...',
    516: 'Bác biết nơi đó sao?',
    517: 'Ừm... phải... nhưng chuyện đó cũng từ lâu lắm rồi...',
    518: 'Ấy chết... ta còn chưa xưng tên nữa!\nTa là...',
    519: '<NAME=CP_0004>.\nRất vui được gặp.',
    520: 'Cậu thanh niên đeo mặt nạ... Đường kiếm của cậu\nvẫn còn hơi thô ráp, nhưng cậu thực sự có bản lĩnh đấy.',
    521: 'Cảm ơn.',
    522: 'Ông cũng nói được câu đó à...',
    523: 'Ta rất ấn tượng đấy! Nhất là với một người\ncòn trẻ như cậu...',
    524: 'Ha ha! Cậu nói trúng tim đen ta rồi!',
    525: 'Ta đã từng gặp ba người các cậu ở đâu đó\ntrước đây chưa nhỉ?',
    526: 'Tôi không nhớ là từng gặp.',
    527: 'Thật sao? Trông cô có nét gì đó quen lắm...',
    528: '...Chắc chỉ là người giống người thôi.',
    529: '......',
    530: 'Ừ, chắc là vậy rồi...\nTa lẩm cẩm mất rồi.',
    531: 'Nhưng cách ăn vận của cô bé kia...\nKhông lẽ cháu là...',
    532: 'Có chuyện gì sao ạ?',
    533: 'À... không, không có gì...\nCơ mà, mấy đứa làm gì ở một ngôi làng hoang tàn thế này?',
    534: 'Chúng tôi muốn đến <NAME=MA_0014_01>.',
    535: 'Chúng tôi muốn tìm ngôi làng gần nhất.',
    536: '<NAME=MA_0014_01> ư?\nMấy đứa sẽ phải băng qua ngọn núi đấy.',
    537: 'Nghe có vẻ hành trình phía trước\nsẽ rất gian nan đây...',
    538: 'Chà, nếu mấy đứa cứ tiếp tục đi về phía bắc,\nsẽ đến ngôi làng Purikka...',
    539: 'Nếu cứ tiếp tục đi về phía bắc,\nmấy đứa sẽ đến ngôi làng Purikka...',
    540: 'Đến đó và nói chuyện với đội trưởng tự vệ đoàn,\nta tin chắc họ sẽ giúp đỡ được mấy đứa.',
    541: 'Ông cũng sống ở đó sao?',
    542: 'Ừm... phải, đại loại vậy...',
    543: 'Nếu bác cũng về hướng đó,\nchúng ta cùng đi chung nhé?',
    544: 'Thôi, ta định đi dạo quanh đây thêm một lát nữa...',
    545: 'Bác chắc là mình sẽ ổn chứ?\nCháu thấy quanh đây có vẻ không có nhiều quái vật lắm...',
    546: 'Ừ, giờ thì không còn nữa rồi...',
    547: 'Không còn nữa sao ạ?',
    548: 'Ừ... Nhờ vào sự chở che của vật hiến tế cả thôi.',
    549: 'Dù sao thì đừng lo cho ta.\nTa đi dạo thế này hàng ngày suốt bao năm qua rồi!',
    550: 'Dạ vâng... Vậy bác nhớ cẩn thận nhé...',
    551: 'Ha ha! Cảm ơn cháu...',
    552: 'Đây hẳn là ngôi làng mà\n<NAME=CP_0004> đã nhắc tới.',
    553: 'Ôi! Các bạn của tôi! Mọi người đều ở đây cả rồi!\nMọi người đều bình an vô sự!',
    554: 'Chúng tôi đã gặp ông trên tàu...',
    555: 'Ngươi thuộc Thương Hội Ma Đạo.',
    556: 'Ngươi là nghệ nhân tạp kỹ lang bạt đó.',
    557: 'Thật mừng vì mọi người vẫn còn nhớ!',
    558: 'Chính là tôi đây! Nào, xin mời bước lại đây!\nThưa quý ông quý bà, các chàng trai cô gái!\nHãy xem tôi xoay chiếc đĩa này đây...',
    559: 'Không phải... Tôi là người của Thương Hội Ma Đạo mà.',
    560: 'Cảm ơn mọi người đã giúp đỡ tôi khi còn ở trên tàu nhé!',
    561: 'Vậy là anh cũng đến được đại lục an toàn rồi.\nSố anh may mắn thật đấy.',
    562: 'Ôi, tôi chẳng thấy may mắn chút nào đâu...\nToàn bộ hàng hóa của tôi đều chìm theo con tàu rồi!',
    563: '(Giải thích về Thương Hội Ma Đạo)',
    564: 'Vì thế, tôi dự định sẽ mở sạp buôn bán\nở đây một thời gian.',
    565: 'Mọi người đang hướng tới <NAME=MA_0014_01> phải không?',
    566: 'Đúng vậy. Nhưng nghe nói muốn tới đó từ đây\nthì phải vượt qua một ngọn núi...',
    567: 'A ha! Chuyện đó thì mọi người không cần lo lắng đâu!\n|\nCó một hệ thống hang động dẫn thẳng đến thành trì đấy!',
    568: 'Thật sao ạ!?',
    569: 'Vâng, đội trưởng có thể mở khóa lối vào cho mọi người.',
    570: 'Ôi, nhẹ cả người...',
    571: 'Mọi người đã chuẩn bị đầy đủ cho chuyến đi chưa?\nHãy chắc chắn chuẩn bị đủ vật phẩm trước khi lên đường nhé!',
    572: 'Và nếu mọi người có bất kỳ nguyên liệu nào thu thập từ quái vật,\nxin hãy bán lại cho Thương Hội Ma Đạo chúng tôi.',
    573: 'Chúng tôi luôn nỗ lực hết mình để đưa ra\nmức giá tốt nhất có thể!',
    574: 'Trong làng mọi người cũng sẽ tìm thấy các bạn hàng của tôi.\nCó thợ rèn, tiệm thuốc, đầu bếp...',
    575: 'Họ đều ở trong quán rượu bên trái lối vào làng,\nnên xin hãy ghé qua ủng hộ họ nữa nhé!',
    576: 'Dạ, xin hỏi...',
    577: 'Gì thế? Có chuyện gì à?',
    578: 'Cô có phải là đội trưởng... không ạ?',
    579: 'Đúng thế... Ta là <NAME=NPC_10050>. Mặt ta trông có gì\nkỳ lạ lắm sao...?',
    580: 'Xin lỗi cô... Cháu không cố ý thất lễ đâu ạ.',
    581: 'Chỉ là cháu chưa từng nghĩ đội trưởng\nlại là một người phụ nữ...',
    582: 'Người lữ hành à?',
    583: 'Chúng tôi muốn tới Floneia.',
    584: '<NAME=MA_0014_01> ư?\nTrông các người chẳng giống bất kỳ thương nhân nào ta từng thấy...',
    585: 'Ta không thể tùy tiện cho một nhóm người\nkhông rõ danh tính đi qua được.',
    586: 'Nếu muốn đến Floneia, các người phải\ngiải thích rõ ràng thân phận của mình.',
    587: 'Chúng tôi là hộ vệ của vật hiến tế.',
    588: 'Mau cho chúng tôi qua ngay!',
    589: 'Ta từng nghe nói tộc người đeo mặt nạ\nlà những lính đánh thuê thiện chiến...',
    590: 'Nhưng ta chưa từng tưởng tượng trong số họ lại có kẻ ngu xuẩn\nđến mức không biết lượng sức mình khi gặp đối thủ!',
    591: 'Nếu ngươi muốn giao chiến, ta sẵn lòng\ntiếp chiêu ngươi.',
    592: 'Xin hãy dừng lại!\nChúng tôi không hề muốn chiến đấu!',
    593: 'Cháu chính là vật hiến tế, còn họ\nlà những người bảo vệ cháu.',
    594: 'Đó là lời bịa đặt hay nhất mà các người nghĩ ra được đấy à?',
    595: 'Từ lần hiến tế trước đến nay còn chưa đầy mười năm đâu!',
    596: 'Chúng cháu không nói dối đâu ạ.',
    597: 'Cô không nhận thấy sao ạ?',
    598: 'Dạo gần đây quái vật trở nên hung hãn hơn rất nhiều,\nvà số lượng của chúng đang tăng lên nhanh chóng.',
    599: 'Nếu không hành động sớm, hậu quả\nsẽ vô cùng khôn lường.',
    600: 'Đó là lý do người ta quyết định tiến hành\nlễ hiến tế sớm hơn thường lệ.',
    601: 'Ừm... ra vậy... và vật hiến tế đó\nchính là cháu sao?',
    602: 'Ta cũng nhận thấy lũ quái vật\nngày càng trở nên hung tợn hơn.',
    603: 'Càng ngày càng khó đối phó với lũ quái vật\nở quanh thị trấn này...',
    604: 'Liệu có phải sức mạnh của nghi lễ hiến tế\nđang dần suy yếu?',
    605: 'Hay đang có điều gì khác bất thường...?',
    606: 'Dạo gần đây ta cũng cảm thấy một nỗi bất an\nkỳ lạ trong lòng...',
    607: 'Nhưng chính vì thế ta lại càng có lý do\nkhông thể để các người đi qua <NAME=MA_0011_01>.',
    608: 'Nhưng tại sao lại thế ạ?',
    609: 'Quái vật trong <NAME=MA_0011_01> còn nguy hiểm hơn\nrất nhiều so với lũ trên mặt đất.',
    610: 'Với tư cách là người chịu trách nhiệm bảo vệ ngôi làng này...',
    611: 'Ta không thể để một vật hiến tế cùng vỏn vẹn\nhai người hộ vệ đi vào chỗ chết được.',
    612: 'Vậy chúng cháu phải làm sao bây giờ ạ?',
    613: 'Ta đang huấn luyện những thanh niên quanh đây\nthành lực lượng tự vệ.',
    614: 'Ta muốn các người ít nhất phải chọn một người trong số họ\nđể đi cùng.',
    615: 'Chúng tôi không cần sự giúp đỡ của ai cả.',
    616: 'Cô tự mình huấn luyện họ sao?',
    617: 'Các vật hiến tế bảo vệ tất cả chúng ta.\nSự an nguy của họ là điều tối quan trọng.',
    618: 'Chỉ hai người các cậu thì làm sao mong bảo vệ\ncho cô bé một cách thỏa đáng được?',
    619: 'Nếu hai người các cậu bỏ mạng, vật hiến tế\nsẽ trở thành mồi ngon cho quái vật!',
    620: 'Các cậu là đội hộ vệ gầy còm, yếu ớt nhất mà ta từng thấy đấy!\nTa chẳng biết phải nói gì hơn nữa...',
    621: 'Lũ quái vật sẽ chẳng rảnh rỗi chờ đợi\nđến khi mọi chuyện thuận lợi cho chúng ta đâu.',
    622: 'Chúng ta phải sẵn sàng chiến đấu chống lại chúng\nbất cứ lúc nào.',
    623: 'Chúng cháu có gặp một người đàn ông ở ngôi làng bỏ hoang gần đây...\nBác ấy cũng thuộc đội tự vệ sao ạ?',
    624: 'Ồ, vậy là các cháu đã gặp <NAME=CP_0004>...\nNói đúng ra thì anh ta hơi khác một chút.',
    625: 'Anh ta từng là thành viên của một đoàn hộ tống vật tế... nhưng...',
    626: 'Thật sao ạ?\nBác ấy từng hộ tống vật hiến tế sao?',
    627: 'Ô, anh ta không kể với các cháu à?\nChuyện đó cũng gần 20 năm trước rồi...',
    628: 'Trông ông ta chẳng giống người từng làm việc đó chút nào...',
    629: 'Có một người giàu kinh nghiệm đi cùng sẽ là sự trợ giúp tuyệt vời...\nCô nghĩ bác ấy có chịu tham gia cùng chúng cháu không?',
    630: 'Ta rất nghi ngờ điều đó đấy...\nAnh ta không còn là người đàn ông như năm xưa nữa rồi.',
    631: 'Ôi... Ra là vậy ạ...',
    632: 'Nói thật lòng thì ta cũng chẳng biết phải làm sao với anh ta nữa...',
    633: 'Kể từ sau chuyến hành hương đó, anh ta chưa từng quay về\nquê hương lấy một lần...\n|\nAnh ta cứ thế ở lại đây suốt ngần ấy năm.',
    634: 'Tại sao lại như vậy ạ?',
    635: 'Chà... có lẽ cháu nên thử hỏi thẳng anh ta xem.',
    636: 'Dù sao thì, để ta giới thiệu các cháu\nvới những người trong đội của ta!',
    637: 'Giờ này chắc họ đang luyện tập ngoài quảng trường làng đấy.\nĐi theo ta.',
    638: 'Tất cả họ đều có thể tự bảo vệ bản thân.\nCác cậu có muốn thử bản lĩnh của họ không?',
    639: 'Được thôi, cho chúng tôi xem năng lực của họ đi.',
    640: 'ĐÂY mà là đội tự vệ sao?',
    641: 'C-cậu nói vậy là có ý gì hả!?',
    642: 'Phải đấy... sao chứ?',
    643: 'Tôi cũng không muốn làm vậy đâu... nhưng xem ra\nchúng ta không còn lựa chọn nào khác rồi.',
    644: 'Hãy để chúng tôi xem thực lực của các cậu...',
    645: 'Hả? Để làm gì cơ chứ?',
    646: 'Nếu các cậu thực sự mạnh mẽ, chúng tôi sẽ để các cậu\ngia nhập đoàn hộ tống vật hiến tế.',
    647: 'C-cái gì? Ngay bây giờ á!?\nNhưng chuyện đó có thật không đấy...? Các người sẽ cho chúng tôi gia nhập đoàn hộ vệ sao?',
    648: 'Cả ba người các cậu có thể xông lên cùng một lúc.\nKhi nào chuẩn bị xong thì chúng ta bắt đầu.',
    649: 'Chúng ta thực sự phải đánh với mấy người này sao?\nTrông họ có vẻ rắn rỏi lắm đấy...',
    650: 'Tớ cũng chẳng thích vẻ ngoài của cái gã đeo mặt nạ kia chút nào...',
    651: 'Không! Tôi muốn trở nên mạnh mẽ hơn!',
    652: 'Tôi sẽ cho họ thấy thực lực của mình... và tôi\nsẽ gia nhập đoàn hộ tống vật hiến tế!',
    653: 'Nhưng từ khi trở về sau chuyến hành trình đó,\n<NAME=CP_0004> đâu còn như trước nữa...',
    654: 'Dù khi trở về chúng ta có được chào đón như những anh hùng...\nNhưng nếu kết cục cũng giống như ông ấy thì...',
    655: 'Cậu bị ngốc à?',
    656: 'Chỉ vì <NAME=CP_0004> bị suy sụp,\nđâu có nghĩa là chúng ta cũng sẽ như thế!',
    657: 'Tôi muốn trở thành anh hùng! Tôi muốn được người đời\nngợi ca trong những truyền thuyết và sử thi!',
    658: 'Dù sao thì đây có thể là cơ hội duy nhất trong đời\nđể chúng ta tham gia vào hành trình của vật hiến tế...',
    659: 'Mấy đứa còn lảm nhảm cái gì thế hả?\nMau mau chuẩn bị tinh thần đi!',
    660: 'Tôi sẽ làm!',
    661: 'Được rồi... Tớ theo các cậu!',
    662: 'Sẽ ổn thôi! Hắn đeo cái mặt nạ đó chỉ để làm bộ ngầu thôi mà!\nNào, xông lên thôi!',
    663: 'Xem ra họ đã sẵn sàng rồi...',
    664: 'Không ổn rồi...\nChúng ta chẳng có lấy một cơ hội thắng...',
    665: 'Tôi chưa từng tưởng tượng đoàn hộ tống vật hiến tế\nlại MẠNH ĐẾN MỨC NÀY...',
    666: 'Đ-đúng vậy... nghĩ lại thì...',
    667: 'Thật thảm hại... Mấy đứa đúng là chẳng thể làm đối thủ của họ được nhỉ?',
    668: 'Đáng tiếc là chúng nó thực sự có quá ít kinh nghiệm thực chiến...',
    669: 'Giờ chúng tôi đi được chưa? Rõ ràng là\nchẳng có ai ở đây đủ tiêu chuẩn cả.',
    670: 'Không, vẫn còn một người nữa...',
    671: 'Thật sao ạ? Người đó đang ở đâu?',
    672: 'Đang đứng ngay trước mặt các người đây.',
    673: 'Ý cô là... cô sẽ đi cùng chúng cháu sao?',
    674: 'Chứ ta còn lựa chọn nào khác nữa đâu?',
    675: 'Nếu không ai khác đủ tiêu chuẩn,\nthì ta phải tự mình đi thôi.',
    676: 'Tôi là cô thì tôi sẽ không làm vậy đâu...',
    677: 'Cô có chắc là mình đủ mạnh không đấy?',
    678: 'Ta chưa già đến mức cần một nhóc con\nmiệng còn hôi sữa như cậu phải bận tâm đâu!',
    679: 'Ta vẫn vung kiếm ngon lành lắm, cảm ơn cậu đã hỏi...\nTa thừa sức tự lo cho bản thân, đừng có mà lo bò trắng răng!',
    680: 'Ồ, nói năng cứng cỏi gớm nhỉ?',
    681: 'Ta có thể đã qua thời kỳ đỉnh cao, nhưng tay kiếm của ta\nchưa hề cùn đi chút nào đâu.',
    682: 'Trong chiến trận, kinh nghiệm và trực giác\nmới là thứ định đoạt tất cả!',
    683: 'Cảm ơn cô. Biết có cô đi cùng, chúng cháu thấy nhẹ lòng hơn rất nhiều.',
    684: 'Quyết định vậy rồi thì ta phải chuẩn bị lên đường thôi...',
    685: 'Nào! Mấy đứa đang làm cái gì thế hả, tính ngủ trưa đấy à!?\nTất cả, làm nhiệm vụ tuần tra ngay cho ta!',
    686: 'Hả? Ngay bây giờ sao ạ?',
    687: 'Chân của em... chúng không chịu nhúc nhích nữa rồi...',
    688: 'Hôm nay cho chúng em nghỉ đi mà...',
    689: 'Xốc lại tinh thần mau!',
    690: 'Sắp tới mấy đứa sẽ phải tự mình\nbảo vệ nơi này suốt một thời gian đấy!',
    691: 'Thứ lỗi nhé, nhưng mấy đứa có thể đợi ở đây một lát được không?\nSẽ không mất nhiều thời gian đâu.',
    692: 'Ta cần đi tuần tra lần cuối, tiện thể vực dậy tinh thần\ncho mấy đứa nhóc này!',
    693: 'Xin mời mọi người cứ về nhà ta nghỉ ngơi cho đến khi ta quay lại nhé.',
    694: 'Chúng ta hãy nhận lời mời của đội trưởng và nghỉ ngơi\ncho đến khi cô ấy quay lại nhé.',
    695: 'Dù chúng ta cũng chẳng có nhiều thời gian\nđể mà ngồi thảnh thơi...',
    696: 'Đường còn dài lắm đấy...\nChúng ta cần tranh thủ nghỉ ngơi mỗi khi có cơ hội.',
    697: 'Được rồi...\nXem ra chúng ta không còn lựa chọn nào khác.',
    698: 'Nghĩ lại thì, thật khó hiểu tại sao bác ấy\nlại chưa từng về nhà dù chỉ một lần...',
    699: 'Có lẽ đã có chuyện gì đó xảy ra trong chuyến hành trình hiến tế chăng...',
    700: 'Ý cô là <NAME=CP_0004> sao?'
}
