# -*- coding: utf-8 -*-
"""Batch 4: Rows 1061 to 1240 (180 lines)"""

batch4_data = {
    1061: 'Anh đeo cái mặt nạ đó trông đáng sợ thật đấy... nhưng hóa ra anh lại là người tốt bụng ghê!',
    1062: 'Tư tưởng lớn gặp nhau rồi đấy.',
    1063: 'Nếu có chuyện gì xảy ra, chúng ta không dám đảm bảo an toàn cho nhóc đâu đấy nhé?',
    1064: 'Hãy dẫn cậu bé theo đi.',
    1065: 'Gì cơ? Thôi nào...',
    1066: 'Dù chúng ta có bỏ em lại đây, em vẫn định lén đi theo bọn chị đúng không?',
    1067: 'Dạ, vâng... Quanh đây nhiều quái vật quá làm em khốn đốn suốt...',
    1068: 'Được rồi...\nVậy <NAME=CP_0005> sẽ đồng hành cùng chúng ta một thời gian nhé.',
    1069: 'Phù!\nThật may là mọi người biết cảm thông...',
    1070: 'Chẳng bù cho ông chú cổ hủ cứng đầu đằng kia chút nào...',
    1071: '......',
    1072: '<NAME=CP_0005> đã đi cùng nhóm của bạn.',
    1073: 'Đây là <NAME=MA_0012_01>.\nCác người đến đây để xin định cư trong làng à?',
    1074: 'Đúng vậy.',
    1075: 'Chúng tôi đến để tìm người.',
    1076: 'Đừng có đùa giỡn nữa,\n<NAME=CP_0001>.',
    1077: 'Chúng tôi đến đây vì đang tìm người ạ.',
    1078: 'Ở đây có người đàn ông nào tên là <NAME=NPC_10080> không ạ?\nKỹ sư trưởng tàu <NAME=NPC_10080>...',
    1079: '<NAME=NPC_10080> ư?\nTôi không nhớ là có ai tên thế...',
    1080: 'Có rất nhiều người qua lại nơi này...\nChúng tôi để họ đến và đi tùy ý.',
    1081: 'Xem ra chúng ta chỉ còn cách\nđi hỏi khắp nơi thôi...',
    1082: 'À không, khoan đã... Thử hỏi ông cụ ở ngôi nhà\ntận cùng góc làng xem.',
    1083: 'Ông ấy ở đây lâu hơn bất kỳ ai,\nnên có thể sẽ biết điều gì đó.',
    1084: 'Dạ, xin hỏi...',
    1085: 'A ha! Cư dân mới đấy à?\nTa là <NAME=NPC_10070>... một ông già rảnh rỗi nhiều thời gian thôi...',
    1086: 'Nếu có bất kỳ điều gì cháu muốn biết về cuộc sống ở ngôi làng này,\nta rất sẵn lòng chỉ bảo.',
    1087: 'Dạ... Không ạ, chúng cháu đến đây là để tìm người...',
    1088: 'Cụ có biết kỹ sư tàu <NAME=NPC_10080> không ạ?',
    1089: '<NAME=NPC_10080> sao? Có chứ, ta biết rất rõ anh ta.',
    1090: 'Thật sao ạ!?',
    1091: 'Anh ta là một người tài năng và rất trọng nghĩa khí.\nAnh ta từng rất thân cận với cựu lãnh chúa của thành trì đấy.',
    1092: 'Chúng cháu đang rất cần một chiếc phi thuyền!\nBác ấy có đang ở trong ngôi làng này không ạ?',
    1093: 'Không, anh ta không có ở đây. Ta đoán chừng anh ta đang ở đâu đó quanh Floneia thôi.',
    1094: 'Anh ta thường hay la cà trong quán rượu ở đó,\ncằn nhằn than vãn với bất kỳ ai chịu lắng nghe.',
    1095: 'Anh ta có thói quen cứ nói chuyện là lại tặc lưỡi liên hồi...',
    1096: 'Tặc lưỡi à? Xem ra chuyến đi này không uổng công rồi...\nNào, chúng ta quay lại thôi, <NAME=CP_0001>.',
    1097: 'Cháu cảm ơn cụ <NAME=NPC_10070> rất nhiều!',
    1098: 'Tuy nhiên, dù các cháu có tìm thấy anh ta, thì anh ta cũng không phải kiểu người chịu nghe theo mệnh lệnh của người khác đâu.',
    1099: 'Mà tại sao các cháu nhất thiết phải cần một chiếc phi thuyền vậy?',
    1100: 'Cô gái này là vật hiến tế.',
    1101: 'Chúng tôi chỉ thích đi thử thôi.',
    1102: 'Hô hô hô! Không cần phải giấu giếm sự thật đâu.\nNếu chỉ là một sở thích bốc đồng...',
    1103: 'Thì các cháu đã chẳng phải cất công lặn lội đi tìm một kỹ sư tàu như thế này.',
    1104: 'Ta tin chắc các cháu đang gánh vác một sứ mệnh cấp bách hơn nhiều.',
    1105: 'Cháu xin lỗi cụ. Bọn cháu không cố ý giấu giếm đâu ạ.',
    1106: 'Cháu là <NAME=CP_0002>, vật hiến tế, còn họ là những hộ vệ của cháu.',
    1107: 'Trời đất...\nRa là vậy sao...',
    1108: 'Cháu đang gánh vác một trọng trách vô cùng to lớn trên vai đấy, cô gái nhỏ.',
    1109: 'Chắc hẳn phải có duyên trời định mới đưa vật hiến tế và đoàn hộ vệ đến tận nơi này...',
    1110: 'Ta có thể hỏi các cháu một câu được không?',
    1111: 'Dạ, câu gì ạ?',
    1112: 'Các vật hiến tế mang lại niềm hy vọng cho muôn dân.',
    1113: 'Nhưng cũng có những kẻ luôn nghi ngờ nghi lễ hiến tế, thậm chí ra sức phản đối nó.',
    1114: 'Chuyến hành trình của các cháu sẽ vô cùng gian nan và hiểm trở,\nvà các cháu thậm chí còn chẳng biết liệu nó có được đền đáp hay không...',
    1115: 'Dẫu vậy, các cháu vẫn sẵn sàng dấn thân để hoàn thành chuyến hành hương này chứ?',
    1116: 'Câu đó chúng tôi thậm chí chẳng cần phải trả lời.',
    1117: 'Ai mà biết được tương lai sẽ ra sao chứ?',
    1118: 'Ta hiểu rồi... Xem ra câu hỏi của ta thậm chí không đáng để các cậu bận tâm trả lời.',
    1119: 'Đúng như những gì người ta kỳ vọng ở những chiến binh dũng cảm được chọn làm hộ vệ cho vật hiến tế...',
    1120: 'Ta có thể tin tưởng vào sự thẳng thắn của các cậu hơn nhiều so với những lời hứa sáo rỗng của những kẻ ba hoa.',
    1121: 'Ta xin lỗi vì đã hoài nghi quyết tâm của các cháu. Xin hãy thứ lỗi cho ta.',
    1122: 'Ta xin lỗi...',
    1123: 'Xem ra các cháu là những người hoàn toàn đáng để tin cậy.',
    1124: 'Có lẽ chính ý trời đã dẫn lối các cháu đến đây vào lúc này...',
    1125: 'Được rồi. Hãy để tấm thân già này góp chút sức mọn giúp đỡ các cháu.',
    1126: 'Hãy đưa thứ này cho kỹ sư tàu <NAME=NPC_10080>.',
    1127: 'Bạn đã nhận được\n"<NAME=ITEM_EVT_002>"\ntừ <NAME=NPC_10070>.',
    1128: 'Đây là gì vậy ạ...?',
    1129: 'Bên trong có viết một chút "phép thuật" nho nhỏ đấy...',
    1130: 'Ta nghĩ chừng đó là đủ để mở mắt cho anh ta rồi.',
    1131: 'Cháu xin cảm ơn cụ, chúng cháu vô cùng biết ơn...\nNhưng...',
    1132: 'Tại sao cụ lại đối xử tốt với chúng cháu như vậy ạ?',
    1133: 'Ta từng phạm phải một sai lầm không thể cứu vãn,\nvà hậu quả là biết bao sinh mạng đã phải nằm xuống.',
    1134: 'Dù ta có cố gắng chuộc lỗi thế nào đi nữa, những sinh mạng ấy cũng không thể sống lại.\nVì vậy, chí ít...',
    1135: 'Ta ước nguyện được giúp đỡ vật hiến tế trên chuyến hành trình...\nđể cứu lấy vô vàn sinh mạng trong tương lai.',
    1136: 'Này nhóc... Nhóc định bám đuôi bọn ta\nđến bao giờ nữa đây hả?',
    1137: 'Hửm? Có chuyện gì sao?',
    1138: 'Hả? À... Chỉ là...',
    1139: 'Suốt từ nãy đến giờ, em cứ có cảm giác\nnhư có ai đó đang theo dõi em...',
    1140: 'Ồ, lại tính làm trò để bọn ta thương hại nhóc nữa đấy à?',
    1141: 'Thương hại tôi á? Tôi có thể yếu đuối, nhưng tôi không cần sự thương hại của ai cả!\nTôi sống cuộc đời của TÔI theo cách của TÔI!',
    1142: 'Ông coi thường tôi quá rồi đấy!?',
    1143: 'Được rồi, được rồi... Chú xin lỗi nhóc. Chú chỉ đùa một chút thôi mà.',
    1144: '......',
    1145: 'Không... Em mới là người phải xin lỗi...',
    1146: 'Cái quái gì thế này... Con này trông chẳng giống bất kỳ con quái vật nào ta từng thấy...',
    1147: 'Nếu thấy kẻ nào khả nghi, kinh nghiệm của ta luôn là tiên hạ thủ vi cường, tính sau...',
    1148: 'Đợi một chút đã!',
    1149: 'Nhóc đang ngáng đường đấy. Tránh ra.',
    1150: 'Không, không sao đâu! Nó ổn mà! Cứ mặc kệ nó đi,\nnó sẽ chẳng làm gì chúng ta đâu!',
    1151: 'Tấn công nó.',
    1152: 'Chờ xem nó làm gì đã.',
    1153: 'Dừng lại đi! Đừng mà! Nó không làm hại chúng ta đâu!',
    1154: '<NAME=CP_0005>...',
    1155: '......',
    1156: 'Được rồi... Chị tin em.',
    1157: 'Dù sao thì nó cũng đâu có lao vào tấn công chúng ta đâu.',
    1158: '<NAME=CP_0002>...',
    1159: 'Cảm ơn anh. Em biết ngay là anh sẽ hiểu mà.\nCái mặt nạ đó đeo vào không phải chỉ để làm cảnh nhỉ?',
    1160: 'Tôi thấy cái mặt nạ đó chẳng liên quan gì đến chuyện này cả...',
    1161: 'Cảm ơn mọi người nhé.',
    1162: 'Nhưng làm sao em biết được vậy?\nLàm sao em biết nó sẽ không tấn công?',
    1163: 'Hả?',
    1164: 'À... Ờ, thì...',
    1165: 'Lần trước đi qua đây em đã nhìn thấy nó rồi...',
    1166: 'Lúc đó nó cũng chỉ lững thững bỏ đi chỗ khác thôi mà!',
    1167: 'Ồ, ra là vậy...',
    1168: '......',
    1169: 'Kỹ sư tàu <NAME=NPC_10080> á?\nChậc chậc! Chưa từng nghe tên bao giờ!',
    1170: 'Cái giọng điệu đó...',
    1171: 'Gì thế? Xong việc rồi đúng không?\nChậc chậc! Mau tránh đường cho người ta đi nhờ cái.',
    1172: 'Hay là các người còn muốn hỏi chuyện gì khác nữa hả?',
    1173: 'Ngươi chính là <NAME=NPC_10080>!',
    1174: 'Chúng tôi cần anh lái chiếc phi thuyền.',
    1175: 'Ặc! S-sao các người lại nói thế chứ?',
    1176: 'Bởi vì chúng tôi nghe nói anh có thói quen\ncứ hễ nói chuyện là lại tặc lưỡi...',
    1177: 'Chậc chậc! Làm gì có cái thói qu--\nÁ...',
    1178: 'Trời đất ạ... Đúng là tự mình lạy ông tôi ở bụi này...',
    1179: 'Tôi không phải kỹ sư tàu gì đâu... Tôi chẳng biết lái con tàu của Lãnh chúa đâu nhé!',
    1180: 'Chưa có ai ở đây nói đó là tàu của Lãnh chúa cả...',
    1181: 'Úi chà...',
    1182: 'Xem ra cậu đã trên cơ hắn rồi đấy, <NAME=CP_0001>...',
    1183: 'Chậc chậc! Thôi được rồi, xem ra bị các người bắt thóp rồi!\nĐúng thế, đúng thế đấy...\nTa chính là <NAME=NPC_10080>, và <NAME=NPC_10080> chính là ta!',
    1184: 'Vậy thì xin bác hãy...',
    1185: 'Không đời nào.',
    1186: 'Ta không ưa tên Lãnh chúa hiện tại <NAME=NPC_10060> đó chút nào...\nTa không có ý định làm theo lệnh của hắn đâu!',
    1187: 'Dù khi đã tuổi già sức yếu, cựu Lãnh chúa vẫn là một bậc nhân từ đức độ,\nđược muôn dân hết lòng kính trọng.',
    1188: 'Thế mà con trai ông ta lại lật đổ chính cha đẻ của mình, các người thấy đấy...',
    1189: 'Tất cả chỉ để hắn có thể vơ vét thêm quyền lực vào tay mình... Chậc chậc!',
    1190: 'Nếu là vì cựu Lãnh chúa thì ta sẵn lòng... chứ bảo ta lái phi thuyền cho tên Lãnh chúa hiện tại thì không bao giờ nhé! Không đời nào!',
    1191: 'Làm ơn đi mà... chắc chắn phải có cách nào đó chứ.\nChúng tôi đang rất vội lên đường...',
    1192: 'Lên đường...? Chuyến đi gì mà vội thế?',
    1193: 'Đại loại chỉ là một chuyến du ngoạn ngắm cảnh...',
    1194: 'Chuyến hành hương hiến tế.',
    1195: 'Thế thì việc gì phải vội? Đi bộ thong thả ngắm cảnh không được à?\nChậc chậc!',
    1196: '<NAME=CP_0001>... Hãy nói sự thật cho bác ấy biết đi,\nchúng ta không cần giấu giếm điều gì cả...',
    1197: 'Cứ nói cho bác ấy biết chúng ta đang thực hiện chuyến hành hương hiến tế...',
    1198: 'Cái gì cơ!?',
    1199: 'Ta hiểu rồi...',
    1200: 'Vậy điều đó có nghĩa là đích đến của các người\nchính là <NAME=MA_0041_01>...',
    1201: 'Hừm... Giờ thì ta hiểu tại sao các người lại cần một chiếc phi thuyền rồi!\nChậc chậc!',
    1202: 'Vậy bác sẽ giúp chúng tôi chứ?',
    1203: 'Ta thấu hiểu hoàn cảnh của các người, nhưng chuyện con tàu lại là một vấn đề hoàn toàn khác!',
    1204: 'Như ta đã nói, ta sẽ không bao giờ điều khiển chiếc phi thuyền đó nữa.',
    1205: 'Nếu ta lái nó, ta biết chắc tên Lãnh chúa kia sẽ lợi dụng nó cho những mưu đồ bẩn thỉu của hắn!',
    1206: 'Anh đúng là cứng đầu thật đấy...',
    1207: 'Ông cụ ở <NAME=MA_0012_01> bảo cháu gửi bác thứ này...',
    1208: 'Bạn đã đưa "<NAME=ITEM_EVT_002>"\ncho <NAME=NPC_10080>.',
    1209: 'Hửm? Cái gì đây?\nChữ viết xấu thế này... Chậc chậc!',
    1210: '......',
    1211: 'Khoan... CÁI GÌ CƠ!?',
    1212: 'Gì thế? Gì thế? Chuyện gì thế ạ?',
    1213: 'B-bức thư này là từ cựu Lãnh chúa của thành trì gửi!',
    1214: 'Ý các người là các người đã gặp Lãnh chúa <NAME=NPC_10070>,\ncựu Lãnh chúa của thành trì này sao!?',
    1215: 'Không lẽ nào...\nÔng cụ đó chính là cựu Lãnh chúa sao?',
    1216: 'Có vẻ đúng là như vậy rồi...',
    1217: 'Trong thư viết gì vậy bác?',
    1218: 'Người bảo ta hãy giúp đỡ các người, và lái phi thuyền cho các người...',
    1219: 'Chậc chậc! Chà, nếu đây đã là thỉnh cầu từ đích thân Lãnh chúa <NAME=NPC_10070>,\nthì ta chẳng có lý do gì để từ chối cả!',
    1220: 'Tuyệt quá rồi!',
    1221: 'Ta sẽ đi trước ra cảng để chuẩn bị mọi thứ!',
    1222: 'Ta sẽ đợi ở bến cảng! Các người mau đi xin giấy phép vào cảng\ntừ tên Lãnh chúa chết tiệt kia đi! Ta chờ đấy!',
    1223: 'A, các cháu đã đến rồi. Ta đã chờ các cháu mãi.',
    1224: 'Chúng cháu đã tìm thấy bác <NAME=NPC_10080>, và...',
    1225: 'Phải, ta vừa mới nhận được báo cáo xong... <NAME=NPC_10080> đã xuất hiện tại bến cảng.',
    1226: 'Tuy nhiên, thật là một bất ngờ lớn...',
    1227: 'Ta chưa từng nghĩ các cháu có thể tìm thấy <NAME=NPC_10080>,\nchưa nói đến việc thuyết phục được anh ta giúp đỡ...',
    1228: 'Đó không phải là do công của chúng cháu đâu ạ.\nChúng cháu đã nhận được sự tương trợ...',
    1229: 'Từ chính cựu Lãnh chúa của thành trì...',
    1230: 'Cựu Lãnh chúa ư...?\nLại là cái lão già bao đồng đó...',
    1231: 'Bao đồng sao ạ...?',
    1232: 'Cả cha ta và ta đều mong muốn bảo vệ muôn dân.',
    1233: 'Nhưng phương pháp của chúng ta lại hoàn toàn mâu thuẫn lẫn nhau...',
    1234: 'Ông ấy không ngừng phản đối kế hoạch của ta,\nvì vậy ta đã "nhã nhặn" mời ông ấy rời đi.',
    1235: 'Kế hoạch của ngài... sao ạ?',
    1236: 'Thôi được rồi... Ta sẽ điều động tàu cho các cháu như đã hứa.',
    1237: 'Tuy nhiên...',
    1238: 'Đích đến của nó sẽ hơi khác biệt một chút.',
    1239: 'Vật hiến tế sẽ đi cùng ta.\nCòn lũ còn lại, xử lý hết cho ta, quân đâu!',
    1240: 'Rõ, thưa Lãnh chúa!'
}
