# -*- coding: utf-8 -*-
"""Batch 3: Rows 881 to 1060 (180 lines)"""

batch3_data = {
    881: 'Vì vậy, đổi lại, tôi phải bảo vệ họ... và để làm được điều đó, tôi phải chiến đấu.',
    882: 'Tôi nhất định phải đảm bảo rằng tất cả chúng tôi sẽ cùng nhau đặt chân tới <NAME=MA_0041_01>.',
    883: 'Ta hiểu rồi...',
    884: 'Hộ tống một vật hiến tế như thế này\nchắc chẳng dễ dàng gì đâu nhỉ?',
    885: 'Chắc chắn là không rồi.',
    886: 'Không, không hẳn vậy.',
    887: 'Dù sao thì chúng ta quay về thôi...',
    888: 'Ta không biết đội trưởng sẽ làm gì ta\nnếu bất kỳ thành viên quý giá nào của cô ấy bị thương đâu!',
    889: 'Nhưng <NAME=CP_0004> ơi...',
    890: 'Nào, đi thôi!',
    891: '<NAME=CP_0001>...',
    892: 'Khi kẻ đó tấn công chúng ta, anh đã không bỏ chạy.',
    893: 'Anh đã đứng dậy, sẵn sàng bảo vệ <NAME=CP_0002>\ncho đến giây phút cuối cùng.',
    894: 'Đừng bận tâm về chuyện đó.',
    895: 'Thực ra lúc đó tôi suýt nữa thì bỏ chạy đấy.',
    896: 'Chà... cảm ơn anh.',
    897: 'Nghe anh nói vậy khiến tôi thấy an tâm hơn phần nào.',
    898: 'Tôi không biết anh đang nói thật hay đùa... nhưng dù sao thì\nkết quả là anh đã không bỏ chạy.',
    899: 'Chừng đó là đủ với tôi rồi.',
    900: 'Nào, trước mắt chúng ta hãy quay lại Purikka đã.',
    901: 'Ta đã nghe mấy đứa trong đội kể lại rồi!\nCác người đã đẩy lùi được tên cầm lưỡi hái đó rồi hả?',
    902: 'Ta rất ấn tượng đấy!',
    903: 'Có khi các người chẳng cần đến hộ vệ\ncũng tự xoay xở tốt...',
    904: 'Dù tất nhiên là chuyện đó sẽ không xảy ra rồi.',
    905: 'Giờ cô đã thấy đỡ hơn chưa ạ? Cô không bị đau ở đâu chứ?',
    906: 'Ồ, ừ. Ta ổn mà...',
    907: 'Chỉ rạn sơ sơ khoảng hai mươi cái xương thôi mà?\nChẳng có gì nghiêm trọng đâu.',
    908: 'Cô có chắc thế này là thứ có thể gọi là "ổn" không đấy...?',
    909: '......',
    910: 'Ta nhìn thấy vẻ mặt của cô bé đó rồi nhé...\n"Cô ta chỉ tổ làm vướng chân chúng ta thôi!" chứ gì?',
    911: '......',
    912: 'Ha ha ha! Đừng lo...\nThật thà là đức tính mà ta rất quý đấy!',
    913: 'Nếu các cháu rời làng và đi về hướng tây bắc,\nsẽ đến <NAME=MA_0011_01>.',
    914: 'Floneia nằm ở phía bên kia hang động. Ta sẽ đợi ở lối vào,\nnên khi nào chuẩn bị xong thì cứ đến đó!',
    915: 'Cứ để cô ấy mở khóa lối vào,\nrồi chúng ta tự mình đi tiếp thôi.',
    916: 'Chúng ta không cần ai làm vướng chân mình cả.',
    917: 'Được rồi!',
    918: 'Xem ra các người đã sẵn sàng lên đường rồi nhỉ.',
    919: 'Dạ... về chuyện đó...',
    920: 'Cuối cùng anh cũng tới rồi đấy à.',
    921: 'Hay là các người thực sự định để một phụ nữ đang bị thương\nđi theo hộ tống vật hiến tế trong chuyến hành trình đấy hả?',
    922: 'Tôi chỉ đến để tiễn họ thôi.',
    923: 'Ta hiểu. Có điều là...',
    924: 'Ở Purikka này không còn chỗ cho anh nữa đâu.',
    925: 'Ta đã nói cho tất cả mọi người biết sự thật rồi!\nThời khắc đó cuối cùng cũng đã đến.',
    926: 'Hóa ra từ trước đến nay đội trưởng đều biết hết...',
    927: 'Ừm... Giờ ta thấy như trút được một gánh nặng ngàn cân trên vai vậy!',
    928: 'Khỉ thật... Sao tôi lại vớ phải một bà sư phụ\nbao đồng đến thế này cơ chứ?',
    929: 'Hừ! Chính ta mới là người bị trừng phạt\nkhi có một tên đệ tử cứng đầu như anh thì có!',
    930: 'Không thể tha thứ cho bản thân vì đã thất bại\ntrong việc bảo vệ vật hiến tế...',
    931: 'Anh tự trừng phạt mình bằng cách cứ tiếp tục\nchiến đấu, chiến đấu, và chiến đấu không ngừng...',
    932: '......',
    933: 'Nỗi hối hận vì đã để vật hiến tế phải chết\nđang giam cầm anh trong quá khứ.',
    934: 'Nhưng anh sẽ không tìm thấy câu trả lời mà mình tìm kiếm\nbằng cách cứ tiếp tục bảo vệ Purikka thế này đâu.',
    935: 'Nếu thực sự có một câu trả lời cho anh,\nthì anh chỉ có thể tìm thấy nó ở <NAME=MA_0041_01> thôi...',
    936: 'Anh sẽ chỉ tìm thấy nó khi đồng hành cùng chuyến hành trình của vật hiến tế\ncho đến tận điểm cuối cùng...',
    937: 'Chẳng phải vậy sao?',
    938: 'Hộc... hộc... May quá, kịp rồi...',
    939: 'Cậu là...',
    940: 'Bác vẫn là... bác vẫn là anh hùng\ncủa ngôi làng này!',
    941: 'Chuyến hành trình hiến tế năm xưa có thất bại hay không\nchẳng còn quan trọng nữa!',
    942: 'Bác đã luôn bảo vệ tất cả chúng cháu suốt ngần ấy năm qua...',
    943: 'Cũng giống như vừa nãy, khi bác xả thân bảo vệ cháu\nkhỏi tên cầm lưỡi hái đó...',
    944: 'Bác đã luôn chiến đấu trong đơn độc\nđể bảo vệ tất cả chúng cháu...',
    945: 'Vậy mà cháu lại gọi bác là kẻ hèn nhát...\nCháu... cháu xin lỗi bác...',
    946: 'Không chỉ riêng ngôi làng này đâu. Anh còn muốn bảo vệ\ncả quê hương của mình nữa...',
    947: 'Đó là lý do tại sao anh ở lại đây,\nvà tiếp tục chiến đấu chống lại lũ quái vật.',
    948: 'Tuy nhiên, ta e rằng việc cầm chân quái vật ở đây\nsẽ không còn đủ nữa rồi. Thời khắc đã điểm...',
    949: '......',
    950: 'Hầy... Chẳng có chuyện gì qua mắt được sư phụ cả nhỉ...',
    951: 'Hơn nữa, ta biết anh sẽ không nỡ để cô bé này phải đơn độc chiến đấu\nđể cứu lấy tương lai của mọi người đâu...',
    952: 'T-tuyệt quá...',
    953: 'Đây là điểm kết thúc cho chuỗi ngày làm "anh hùng"\ncủa ngôi làng này đối với anh rồi...',
    954: 'Chẳng phải vậy sao, <NAME=CP_0004>?',
    955: 'Ừ, sư phụ nói đúng...',
    956: 'Nhưng linh hồn ta vẫn sẽ ở lại đây... Ta muốn các cậu tiếp bước ta,\nvà tiếp tục bảo vệ ngôi làng này.',
    957: 'Thật sao, <NAME=CP_0004>?\nBác sẽ đi cùng chúng cháu chứ?',
    958: 'Nếu cô bé cần sự giúp đỡ của ta,\nta rất sẵn lòng giúp...',
    959: 'Miễn là cậu cũng thấy ổn với chuyện đó,\n<NAME=CP_0001>.',
    960: 'Rất hoan nghênh ông.',
    961: 'Tùy ông muốn làm gì thì làm.',
    962: 'Cảm ơn cậu. Ta hứa sẽ bảo vệ <NAME=CP_0002>,\nbằng bất cứ giá nào.',
    963: 'Chuyến hành hương này đúng là thảnh thơi thoải mái thật đấy nhỉ...\nTa nghĩ mình sẽ hòa nhập rất nhanh thôi.',
    964: 'Mọi chuyện ở đây cứ để chúng ta lo, đừng bận tâm...\n|\nVà lần tới khi trở về, anh nhất định phải hoàn thành trọn vẹn hành trình của mình đấy.',
    965: '<NAME=CP_0004> đã gia nhập nhóm của bạn.',
    966: 'Thứ này chính là lý do đội trưởng\nkhông muốn cho các cháu đi qua chỉ với hai người hộ vệ đấy.',
    967: 'Ý ta là... có thêm người thì việc để vật hiến tế\ntẩu thoát một mình sẽ dễ dàng hơn...',
    968: 'Nhưng nếu chúng ta còn không vượt qua nổi nơi này,\nthì sẽ chẳng đi đến đâu được cả.',
    969: 'Nó đến rồi kìa!',
    970: 'Phù... Vậy là qua khỏi đây,\nchúng ta sẽ tới Floneia sao?',
    971: 'Ừ, đúng vậy...',
    972: 'Đi thôi. Chúng ta cần bù lại khoảng thời gian\nđã lãng phí!',
    973: 'Lãnh chúa hiện tại của thành trì này được cho là một người rất có trách nhiệm,\nvà được người dân vô cùng kính trọng.',
    974: 'Có thể ngài ấy sẽ giúp đỡ được chúng ta...',
    975: '<NAME=MA_0012_01> nằm ở phía bên kia của <NAME=MA_0013_01>\nvề hướng bắc nơi này.',
    976: 'Người ốm đau và thương tật đều được chăm sóc chu đáo,\nvà những ai không nơi nương tựa đều được đón tiếp nồng hậu.',
    977: 'Ôi... nhưng... làng của chúng tôi đã bị quái vật tấn công...',
    978: 'Chúng tôi chỉ kịp chạy trốn với manh áo trên lưng... nên... chúng tôi...',
    979: 'Ồ, chỉ có thế thôi sao? Không cần phải lo lắng về tiền bạc đâu!\nLãnh chúa <NAME=NPC_10060> là một người vô cùng nhân từ!',
    980: 'Ôi trời... Lãnh chúa quả thực là một bậc vĩ nhân...',
    981: 'Cháu có thể kết bạn mới được không ạ?',
    982: 'Được chứ, chú tin là cháu sẽ có thêm rất nhiều bạn đấy.',
    983: 'He he... Tuyệt quá!\nLãnh chúa vạn tuế!',
    984: 'Người này sẽ dẫn đường cho các bạn về làng.',
    985: 'Cảm ơn ngài... cảm ơn ngài rất nhiều vì tất cả mọi chuyện...',
    986: 'Hửm? Các ngươi cũng muốn tới <NAME=MA_0012_01> sao?',
    987: '<NAME=MA_0012_01>?',
    988: 'Không phải sao? Vậy các ngươi có việc gì\nở Floneia này?',
    989: 'Nếu muốn được phép vào thành trì,\ntrước tiên các ngươi phải khai rõ danh tính.',
    990: 'Chúng tôi đi cùng vật hiến tế.',
    991: 'Mau dẫn chúng tôi đi gặp Lãnh chúa!',
    992: 'V-vật hiến tế sao!?',
    993: 'Các ngươi to gan thật đấy, chưa thèm xưng danh tính\nmà đã đòi diện kiến Lãnh chúa!',
    994: '<NAME=CP_0001>, đợi đã...',
    995: 'Hãy để em nói chuyện với anh ấy. Chúng ta không có gì phải giấu giếm cả.',
    996: 'Tôi tên là <NAME=CP_0002>.',
    997: 'Tôi đang trên đường tới <NAME=MA_0041_01>\nđể dâng hiến bản thân làm vật tế.',
    998: 'Chúng tôi đến đây với hy vọng sẽ được\nLãnh chúa tương trợ.',
    999: 'Cái gì cơ!?',
    1000: 'Đáng lẽ cô phải nói điều đó sớm hơn chứ!\nHy vọng tôi chưa làm gì mạo phạm...',
    1001: 'Xin mời vào. Lãnh chúa <NAME=NPC_10060> đang ở trong lâu đài\nphía bắc thị trấn.',
    1002: 'A, chào mừng...\nBinh lính của ta đã giải thích tình hình cho ta rồi.',
    1003: 'Vậy cô bé chính là vật hiến tế lần này sao?',
    1004: 'Vâng ạ. Cháu là <NAME=CP_0002>.',
    1005: 'Ta nhận được tin báo tàu của các cháu bị đắm,\nvà đã lo sợ điều tồi tệ nhất...',
    1006: 'Ta rất nhẹ nhõm khi thấy cháu vẫn bình an vô sự!',
    1007: 'Cháu xin cảm ơn ngài.',
    1008: 'Không cần phải cảm ơn ta đâu...',
    1009: 'So với quái vật, con người là những sinh linh yếu đuối.\nBởi vậy, họ cần được chở che và bảo vệ.',
    1010: 'Với tư cách là vật hiến tế, cháu hiến dâng sinh mạng của mình\nđể bảo vệ cho toàn cõi đại lục này...',
    1011: 'Với tư cách là lãnh chúa của thành trì này, ta phải làm việc\nđể bảo vệ cho thần dân của ta...',
    1012: 'Dù quy mô có khác biệt to lớn,\nnhưng mỗi chúng ta đều đang đảm nhận một vai trò thiêng liêng.',
    1013: 'Vâng, đúng như vậy ạ...',
    1014: 'Thật may mắn là ở đây chúng ta vẫn còn một chiếc phi thuyền\ncó thể vận hành được.',
    1015: 'Ta sẽ cho người đưa các cháu đến càng gần <NAME=MA_0041_01> càng tốt.',
    1016: 'Cháu vô cùng cảm kích lòng tốt của ngài.',
    1017: 'Tuy nhiên...',
    1018: 'Có một số trở ngại khiến ta không thể điều tàu xuất phát ngay được...\n|\nTa e rằng các cháu sẽ phải chờ đợi một thời gian ngắn.',
    1019: 'Có chuyện gì bất ổn sao ạ?',
    1020: '<NAME=NPC_10080>, kỹ sư trưởng tàu, hiện đang mất tích.',
    1021: 'Không có anh ta thì phi thuyền không thể cất cánh được.',
    1022: 'Anh ta là một người rất tài năng... nhưng tính khí lại vô cùng cổ quái.\nKhông biết anh ta lại trốn ở đâu rồi nữa...',
    1023: 'Dù sao thì quân của ta cũng sẽ sớm tìm ra anh ta thôi. Ngay khi tìm thấy,\nta sẽ lệnh cho phi thuyền sẵn sàng xuất phát ngay lập tức!',
    1024: 'Cho đến lúc đó, xin các cháu cứ tự nhiên nghỉ ngơi tại thị trấn này.',
    1025: 'Chà... Vậy là kỹ sư tàu của họ đang mất tích nhỉ...?',
    1026: 'Hy vọng không có chuyện gì mờ ám đang diễn ra...',
    1027: 'Mờ ám ư...?',
    1028: 'Đã khá lâu kể từ khi chúng ta bắt đầu chuyến hành trình này rồi.',
    1029: 'Trong suốt thời gian qua, quái vật ngày càng tăng về số lượng,\nvà ngày càng trở nên hung tợn hơn...',
    1030: 'Hy vọng chúng ta không phải tìm một con đường khác\nđể tiếp tục chuyến đi...',
    1031: 'Khỉ thật, cô toàn nghĩ đến những điều đen đủi thôi nhỉ...',
    1032: 'Chúng ta chỉ cần làm hết sức mình để đảm bảo điều đó không xảy ra là được.',
    1033: 'Chúng ta hãy đi tìm <NAME=NPC_10080>.',
    1034: 'Chúng ta hãy cứ nghỉ ngơi thảnh thơi đi.',
    1035: 'Ừ, ý kiến hay đấy. Dù sao thì cũng tốt hơn là ngồi đợi vu vơ ở đây.',
    1036: 'Ta đoán vậy... nhưng sau những gì cô nàng u ám này nói,\nta chẳng thấy thảnh thơi chút nào cả...',
    1037: 'Ta chẳng có chút manh mối nào về việc làm sao để tìm ra\nmột tay kỹ sư mà chúng ta chưa từng gặp mặt bao giờ...',
    1038: 'Nhưng nếu chúng ta tìm được dù chỉ một manh mối nhỏ,\nđiều đó cũng sẽ giúp đẩy nhanh thời gian khởi hành lên một chút...',
    1039: 'Chúng ta hãy thử đi hỏi thăm quanh đây xem có người dân nào\nbiết <NAME=NPC_10080> này có thể ở đâu không nhé.',
    1040: 'Vâng, bác nói đúng đấy. Có thể ai đó sẽ biết điều gì đó,\nchúng ta hãy đi dạo quanh thị trấn một vòng xem sao.',
    1041: 'Nhìn kìa! Cậu bé đằng kia! Cậu ấy đang bị quái vật tấn công!',
    1042: 'Một đứa nhóc làm cái gì một mình ở một nơi như thế này chứ!?',
    1043: 'Phù... Cảm ơn nhé!\nSuýt chút nữa thì toi rồi...',
    1044: 'Có chuyện gì thế? Cháu bị lạc à?',
    1045: 'Lạc á? Không đời nào! Cháu đang trên đường đi du hành đấy!',
    1046: 'Du hành sao? Em định đi đâu?',
    1047: 'Đến <NAME=MA_0041_01>.',
    1048: 'Khoan, khoan đã... Nhóc có biết <NAME=MA_0041_01>\nchính xác là nơi như thế nào không đấy?',
    1049: 'Nơi đó tuyệt đối không phải chỗ dành cho một đứa trẻ\nđi du hành một mình đâu.',
    1050: 'Đừng có gọi tôi là đứa trẻ nữa được không!\nTên tôi là...',
    1051: '<NAME=CP_0005>!\nGiờ thì đừng có đối xử với tôi như con nít nữa, rõ chưa!?',
    1052: 'Chị xin lỗi, <NAME=CP_0005>.\nBọn chị cũng đang đến đó đấy... đến <NAME=MA_0041_01>.',
    1053: 'Thật sao!? Thế thì em đi cùng mọi người luôn!',
    1054: 'Này, đợi một chút đã!\nNhóc nghĩ chuyện này là trò đùa đấy à?',
    1055: 'Đợi đã...',
    1056: 'Ít nhất chúng ta cũng phải đưa cậu bé đến một nơi an toàn chứ...',
    1057: 'Chúng ta đâu thể cứ thế bỏ mặc cậu bé ở đây được, đúng không?',
    1058: 'Muốn làm gì thì làm.',
    1059: 'Tôi không nghĩ đó là một ý hay.',
    1060: 'Cảm ơn nhé!'
}
