# -*- coding: utf-8 -*-
"""Batch 2: Rows 701 to 880 (180 lines)"""

batch2_data = {
    701: 'Vâng...',
    702: 'Này, hay là chúng ta thử nhờ\n<NAME=CP_0004> đi cùng luôn đi?',
    703: 'Sao cô lại để tâm đến ông ta nhiều thế?\nVì ông ta từng có kinh nghiệm làm hộ vệ cho vật hiến tế à?',
    704: 'Chà, tất nhiên đó cũng là một lý do...',
    705: 'Tôi cũng không biết nữa... chỉ là ở bác ấy có điều gì đó...\nkhiến tôi cảm giác như bác ấy đang cần sự giúp đỡ...',
    706: 'Được rồi. Khi nào đội trưởng quay lại\nchúng ta sẽ tính tiếp.',
    707: 'Được rồi...',
    708: 'Cô có thấy cô ấy đi hơi lâu không?',
    709: 'Ừ, đúng vậy thật...\nCô ấy bảo chỉ đi tuần tra lần cuối thôi mà...',
    710: 'C-cứu với!',
    711: 'Ai đó làm ơn giúp với!',
    712: 'Có chuyện gì xảy ra sao?',
    713: 'Có vẻ là vậy... Tiếng hét đó hình như\nphát ra từ cổng vào làng.',
    714: 'Đội trưởng!',
    715: 'Cô ấy không nguy hiểm đến tính mạng đâu, nhưng vết thương khá nặng đấy.\nHãy khiêng cẩn thận.',
    716: 'Còn mấy đứa này thì không phải lo,\nchúng chỉ bị sợ đến mức bủn rủn chân tay thôi.',
    717: 'Rốt cuộc chuyện quái quỷ gì đã xảy ra vậy?',
    718: 'Một gã đàn ông vác lưỡi hái khổng lồ\nđột nhiên lao vào tấn công chúng tôi!',
    719: 'Đội trưởng đã bảo vệ chúng tôi... và giờ...',
    720: 'Ta tình cờ đi ngang qua thì thấy\nđội trưởng đã bị đánh trọng thương!',
    721: 'Nên ta vội cõng cô ấy lên lưng\nvà lôi ba đứa này chạy thục mạng về đây.',
    722: 'Khỉ thật! Sao ông lại bỏ chạy hả!?',
    723: 'Đáng lẽ ông phải chiến đấu với hắn chứ!\nChẳng phải ông từng là anh hùng sao!?',
    724: 'Ta vừa chạy vừa lo thoát thân đã là may lắm rồi!\nLàm sao ta có cửa đọ lại với cái thứ quái thai như thế chứ!',
    725: 'Bỏ đi! Tôi đúng là thằng ngu\nkhi đi trông chờ vào sự giúp đỡ của ông!',
    726: 'Tên cầm lưỡi hái đó có thể vẫn còn ở Serendale...',
    727: 'Tôi sẽ báo thù cho đội trưởng...\nTôi thề bằng danh dự của đội tự vệ!',
    728: 'Này! Đứng lại đã, thằng nhóc kia!',
    729: 'Khỉ thật...',
    730: 'Hai đứa chăm sóc vết thương cho đội trưởng đi.\nChừng đó việc chắc làm được chứ hả?',
    731: 'Giờ thì... ta khuyên mấy đứa câu này vì sự an toàn của mấy đứa thôi...\nMấy đứa nên rời khỏi đây ngay đi.',
    732: 'Có vẻ như tên quái dị đó nhắm vào vật hiến tế...',
    733: 'Và người đó chính là cháu, đúng không cô bé?',
    734: 'Vậy ý bác là... tại cháu mà đội trưởng...',
    735: 'Đừng để bụng chuyện đó.',
    736: 'Hành trình của vật hiến tế vốn dĩ\nlà như thế đấy.',
    737: 'Vậy là có kẻ đang muốn cản trở\nchuyến hành hương này nhỉ?',
    738: 'Nghe có vẻ hơi giống một người khác mà tôi biết đấy...',
    739: 'Gật đầu',
    740: 'Giả vờ ngơ ngác',
    741: 'Dù chúng ta có muốn rời đi thì trước khi đi đâu,\nchúng ta cũng cần mở khóa lối vào hang động đã...',
    742: 'Hơn nữa, đội trưởng từng nói cô ấy sẽ đi cùng chúng ta\nvì đoàn hộ vệ của chúng ta quá ít người.',
    743: 'Hết cách rồi... Cô ấy sẽ cần phải\nnằm tịnh dưỡng hoàn toàn đấy.',
    744: 'Vậy chúng ta phải làm sao bây giờ?\nCô ấy bảo sẽ không cho chúng ta qua nếu không tăng thêm quân số.',
    745: '<NAME=CP_0004>... Cháu nghe nói bác từng hộ tống thành công\nmột vật hiến tế trong chuyến hành trình.',
    746: '......',
    747: 'Bác có thể giúp chúng cháu được không ạ?',
    748: 'Xin lỗi...',
    749: 'Nhưng hành trình của ta đã kết thúc từ lâu lắm rồi.',
    750: 'Khi nào đội trưởng tỉnh lại, các cháu cứ nhờ cô ấy\nmở khóa cửa hang rồi tiếp tục lên đường.',
    751: 'Giờ ta có chút việc bận ở Serendale, xin phép đi trước...',
    752: 'Sao đây? Chúng ta nên làm gì bây giờ?',
    753: 'Đi theo <NAME=CP_0004>.',
    754: 'Đợi đội trưởng tỉnh lại.',
    755: 'Ý cậu là chúng ta nên cố thuyết phục\nđội trưởng đưa chìa khóa cho chúng ta à?',
    756: 'Với quân số vẫn giữ nguyên như thế này sao...\nThôi được, xem ra chúng ta không còn lựa chọn nào khác.',
    757: 'Không... Em nghĩ đó không phải là ý hay đâu.',
    758: '<NAME=CP_0001>, <NAME=CP_0003>...\nEm biết cả hai người đều rất mạnh mẽ.',
    759: 'Nhưng hai người cũng rất quan trọng đối với em...\nHai người là bạn đồng hành của em.',
    760: 'Em muốn hai người kết thúc chuyến đi này một cách an toàn.\nĐể làm được điều đó, chúng ta cần mọi sự giúp đỡ có thể.',
    761: 'Và "sự giúp đỡ" đó, ý em là <NAME=CP_0004> sao?',
    762: 'Chà, có lẽ em nói đúng. Khi mới gặp ông ta,\ntôi cũng không chắc chắn lắm...',
    763: 'Nhưng cách ông ấy đưa đội trưởng và những người khác trở về an toàn như thế...\n|\nÔng ấy rất mạnh mẽ, và rõ ràng là người có thể giữ được bình tĩnh trong tình huống khẩn cấp.',
    764: 'Nhưng ngay cả khi chúng ta đuổi theo ông ta,\nem có nghĩ ông ta sẽ đồng ý đi cùng không?',
    765: 'Em muốn nói chuyện với bác ấy nhiều hơn.',
    766: 'Cảm giác như bác ấy đang gánh trên vai một gánh nặng nào đó...\nEm có linh cảm như vậy...',
    767: 'Và em nghĩ điều đó có thể liên quan đến lý do\ntại sao bác ấy không chịu đi cùng chúng ta.',
    768: 'Dù sao đi nữa, nếu chúng ta không hành động,\nkẻ đã tấn công đội trưởng sẽ còn làm hại thêm nhiều người khác.',
    769: 'Em biết <NAME=CP_0004> đã nói như vậy...',
    770: 'Nhưng em không muốn mọi người phải chịu đau khổ\nchỉ vì em.',
    771: 'Em xin lỗi vì đã cố chấp như vậy...',
    772: 'Không sao đâu.',
    773: 'Đành vậy thôi...',
    774: 'Đúng là phong cách của em,\n<NAME=CP_0002>...\n|\nĐược rồi, chúng ta hãy đuổi theo <NAME=CP_0004>.',
    775: 'Tuyệt quá...!',
    776: 'Không lẽ việc quanh đây có rất ít quái vật\nlại là...',
    777: 'Nhờ có <NAME=CP_0004>.',
    778: 'Nhờ có vật hiến tế.',
    779: 'Vâng, em cũng nghĩ như vậy.',
    780: '<NAME=CP_0004> cũng nói như vậy... nhưng em nghĩ\nlý do thực sự lại khác.',
    781: 'Em nghĩ có lẽ là vì <NAME=CP_0004>\nvẫn luôn âm thầm chiến đấu đuổi chúng đi, giống như lúc này...',
    782: 'Hóa ra đó là lý do lần đầu gặp mặt,\nông ta lại kiệt sức đến thế...',
    783: 'Chẳng lẽ đây là việc ông ta vẫn làm suốt từ khi\ntrở về sau chuyến hành trình hiến tế sao?',
    784: 'Nhưng tại sao bác ấy lại làm như vậy chứ...?',
    785: 'Để bảo vệ ngôi làng.',
    786: 'Để che giấu điều gì đó.',
    787: 'Tất nhiên là có điều đó rồi... nhưng em nghĩ\ncòn có một lý do khác nữa.',
    788: 'Người dân trong làng luôn nghĩ rằng\ncuộc sống bình yên của họ là nhờ vào vật hiến tế.',
    789: '<NAME=CP_0004> chưa từng quay trở về quê hương,\nmà ở lại đây tiếp tục chiến đấu đẩy lùi quái vật...',
    790: 'Liệu có phải là vì bác ấy không muốn ai nghi ngờ\nvề sự bảo hộ của vật hiến tế không?',
    791: 'Nếu đúng như vậy... thì điều đó có nghĩa là...',
    792: 'Phần còn lại thì chúng ta phải\nxác nhận trực tiếp với ông ấy thôi.',
    793: 'Vâng, đúng vậy...\nĐi thôi, <NAME=CP_0001>.',
    794: 'Ông đứng ở đó chắn hết cả lối đi rồi đấy...',
    795: 'Thôi nào, đâu cần phải gay gắt thế.\nNgười ta đi dạo một chút cũng không được sao?',
    796: 'Rốt cuộc ông suốt ngày làm cái gì thế hả?\nCứ lượn lờ quanh pháo đài suốt như vậy...',
    797: 'Anh hùng cái nỗi gì? HỰ!\nÔng nên học tập đội trưởng một chút đi thì hơn!',
    798: 'Ha ha... Cậu nói trúng tim đen ta rồi, nhóc con.\nTa chẳng cãi lại được câu nào.',
    799: 'Đội trưởng từng nói ông là người đàn ông đáng tin cậy nhất mà cô ấy biết...',
    800: 'Tôi cũng từng tin tưởng ông...\nTôi từng ngưỡng mộ ông... nhưng giờ thì...',
    801: 'Đáng tin cậy à?\nChà, e là ta không gánh nổi từ đó đâu...',
    802: 'Bác... <NAME=CP_0004>...',
    803: 'Gì thế? Đội trưởng đã tỉnh lại rồi à?',
    804: 'Xin hãy để cháu cầu xin bác thêm một lần nữa...\nXin bác hãy đồng hành cùng chúng cháu trong chuyến hành trình này...',
    805: 'Ta đã nói câu trả lời của ta rồi mà...\nThứ lỗi nhé, nhưng ta không thể.',
    806: 'Hành trình của ta đã kết thúc rồi.',
    807: 'Không đúng.',
    808: 'Nếu đúng là vậy, thì tại sao bác không trở về\nquê hương sau chuyến hành hương đó?',
    809: 'Tại sao ta không trở về nhà ư...?',
    810: 'Hẳn phải có lý do nào đó.',
    811: 'Chắc chỉ vì ông ta không thích về thôi.',
    812: 'Không... em không nghĩ vậy.\nBác ấy sẽ không liều mạng như thế này mà không có lý do.',
    813: 'Có một lý do khiến bác không thể trở về,\nphải không ạ...?',
    814: 'Một lý do sao...?',
    815: 'Kể từ khi bác trở về sau chuyến hành trình đó...',
    816: 'Bác đã liên tục tiêu diệt tất cả quái vật\nlại gần pháo đài, đúng không ạ?',
    817: 'Tại sao bác lại phải làm như thế?',
    818: 'Để che giấu sự thật.',
    819: 'Ông ta chỉ thích đi săn quái vật thôi!',
    820: 'Nếu đó là lý do, tại sao bác ấy lại chiến đấu\nđến mức kiệt sức sắp ngất đi như vậy?',
    821: 'Đó là vì bác buộc phải làm thế để giữ kín sự thật,\nphải không ạ?',
    822: 'Giữ kín sự thật ư...?',
    823: 'Nếu chuyến hành hương thành công tốt đẹp,\nthì đáng lẽ sẽ không có nhiều quái vật đến thế.',
    824: 'Nhưng thực tế lại không phải vậy... và đó là lý do\nbác phải tiếp tục chiến đấu chống lại chúng.',
    825: 'Và đó là bởi vì chuyến hành trình của vật hiến tế\nmà bác đã từng hộ tống...',
    826: 'Đã thành công.',
    827: 'Đã thất bại.',
    828: 'Thật đáng buồn, nhưng em nghĩ không phải như vậy đâu...',
    829: 'Thực ra, chuyến hành hương đó đã thất bại...',
    830: 'Đó là lý do tại sao bác không thể trở về quê hương.',
    831: 'Nên bác đã ở lại đây, và tiếp tục chiến đấu đẩy lùi lũ quái vật...',
    832: 'Để người dân không phải hoang mang lo sợ, và khiến họ tin rằng\nsự bảo hộ của vật hiến tế vẫn đang tiếp diễn.',
    833: '......',
    834: 'Nhưng đây không còn là vấn đề của riêng Purikka nữa rồi.',
    835: 'Cứ đà này, toàn bộ đại lục sẽ sớm tràn ngập quái vật.',
    836: 'Bác không muốn hoàn thành trọn vẹn chuyến hành trình của mình sao, <NAME=CP_0004>?',
    837: '......',
    838: 'Cháu xin bác... Chúng cháu cần bác.\nChúng cháu cần sức mạnh của bác.',
    839: 'Thôi đi, đừng nói nữa...',
    840: 'Ta chẳng có sức mạnh nào để cho các người cả.\nTa không thể bảo vệ cô bé đâu...',
    841: 'Này! Những gì cô ấy vừa nói là thật sao!?\nSao ông có thể làm vậy được chứ!?',
    842: 'Ý ông là ông đã lừa dối tất cả chúng tôi suốt thời gian qua sao?\nÔng đê tiện đến mức nào nữa đây!?',
    843: 'Anh hùng cái nỗi gì? Bớt giỡn đi! Ông chỉ là một KẺ HÈN NHÁT,\nđúng là như thế! Một tên hèn nhát và dối trá!',
    844: 'Ta... ta chỉ...',
    845: 'Hả! Ch-chuyện gì đang xảy ra thế này!?',
    846: '......',
    847: 'Tránh ra sau lưng ta mau.',
    848: 'Không đời nào! Tôi việc gì phải trốn sau lưng một kẻ như--',
    849: 'Ngậm miệng lại và làm theo lời ta đi...\nNếu nhóc không muốn bỏ mạng tại đây.',
    850: 'Ta đã tìm thấy ngươi rồi... vật hiến tế...',
    851: 'Không lẽ đây chính là...',
    852: 'Tên quái vật đã tấn công đội trưởng!',
    853: '<NAME=CP_0004>, xin hãy đưa cậu ấy đến nơi an toàn!',
    854: 'Ở đây cứ để chúng tôi lo!',
    855: 'Cô nói cái gì thế hả!?\nCô cũng phải chạy đi chứ!',
    856: 'Không... Chúng tôi sẽ chiến đấu!',
    857: 'Chỉ có thế thôi sao?',
    858: '<NAME=CP_0003>!!!',
    859: 'Đã hạ được một đứa...',
    860: 'Lì lợm hơn ta tưởng đấy...\nNhưng tới đây là kết thúc rồi...',
    861: '<NAME=CP_0001>!!!',
    862: 'Kết thúc rồi...',
    863: 'Bỏ tay ra khỏi họ mau!',
    864: 'A... Ngươi...',
    865: 'Vật hiến tế phải bị tiêu diệt!',
    866: 'Ngươi nghĩ ta sẽ để ngươi toại nguyện sao!?',
    867: 'Cái gì!?',
    868: '<NAME=CP_0001>!',
    869: 'Ư... Khốn kiếp...',
    870: 'Xem ra cơ thể này vẫn chưa hoàn thiện...',
    871: 'Hắn biến mất rồi...',
    872: 'Cảm ơn em, <NAME=CP_0002>...\nEm đã cứu mạng bọn tôi đấy.',
    873: 'Thật may là hai người đều bình an.\nEm lúc đó hoảng quá... em...',
    874: 'Mọi người đỉnh thật đấy! Cái tên quái vật đó\nhoàn toàn không thể làm gì được mọi người!',
    875: 'Cháu có bị thương không?',
    876: 'Dạ không... Đều nhờ có bác cả đấy,\n<NAME=CP_0004>.',
    877: 'Tại sao cháu lại không chạy đi?',
    878: 'Cháu không thể cứ thế bỏ chạy và bỏ mặc họ lại phía sau được.',
    879: 'Kể cả khi hộ vệ của cháu bị giết, cháu cũng phải tự cứu lấy bản thân mà chạy trốn...\n|\nĐó là một trong những thiết luật của chuyến hành hương hiến tế.',
    880: 'Nhưng họ đã hứa với cháu... họ đã hứa rằng\nsẽ đồng hành cùng cháu đến tận cuối chặng đường.'
}
