# -*- coding: utf-8 -*-
"""Batch 5: Rows 1241 to 1405 (165 lines)"""

batch5_data = {
    1241: 'Chà, chà... May mắn thật đấy. Ta không ngờ nhóc con cũng ở đây...',
    1242: '!',
    1243: 'Ta đã cho người giám sát những kẻ thuộc chủng tộc quý hiếm, nhằm mục đích bắt sống ngươi sau này...',
    1244: 'Chủng tộc quý hiếm?',
    1245: 'Nhưng ta không bao giờ ngờ được rằng ngươi lại tự mình dâng tới tận miệng thế này! Ngươi đã giúp ta tiết kiệm được khối công sức đấy...',
    1246: 'Dòng máu quý hiếm của các ngươi rất có giá trị, và cực kỳ hữu dụng khi mang ra trao đổi giao dịch...',
    1247: 'Oa ha ha...\nTa quả là một kẻ may mắn!',
    1248: 'N-này! Cái quái gì--',
    1249: 'Các người đang làm cái gì thế hả!?',
    1250: 'Chỉ có bấy nhiêu ma lực thôi sao?',
    1251: 'Đừng có tự mãn quá sớm, thưa Lãnh chúa...',
    1252: 'Nhanh lên nào, mau lên!\nHọ chắc chắn chưa thể đi xa được đâu!',
    1253: 'Nếu hắn định đưa họ lên phi thuyền,\nthì chắc chắn hắn đã hướng ra bến cảng rồi!',
    1254: 'Các người đang ngáng đường đấy! Tránh ra mau!',
    1255: 'Lãnh chúa đã hạ lệnh bắt giữ tất cả các người!',
    1256: 'Xem ra chúng ta không còn lựa chọn nào khác...\nPhải dẹp đường mà xông qua thôi!',
    1257: 'Mở cửa ra!',
    1258: 'Tôi rất tiếc, nhưng Lãnh chúa đã ban nghiêm lệnh\ntuyệt đối không để bất kỳ ai qua cổng...',
    1259: 'Khỉ thật! Ta chịu hết nổi rồi đấy!\nChính tên Lãnh chúa của các người mới là kẻ có vấn đề!',
    1260: 'Vệ binh đâu!',
    1261: 'Thấy chưa? Các người không cản nổi bọn ta đâu!',
    1262: 'K-không được!',
    1263: 'Không ai được phép vào bến cảng\nnếu không có sự cho phép của Lãnh chúa!',
    1264: 'Được rồi, nói thế này chẳng đi đến đâu cả...',
    1265: 'Khoan đã...',
    1266: 'Để ta nói chuyện với họ xem sao.',
    1267: '<NAME=NPC_10070>!',
    1268: 'N-ngài là... Cựu Lãnh chúa tiền nhiệm!?',
    1269: 'Ngài vẫn còn sống sao... Thật không thể tin nổi...',
    1270: 'Ta sẽ giải thích mọi chuyện ngọn ngành sau.',
    1271: 'Trước mắt, xin hãy để những người này đi qua.\nHọ là những người bạn tốt của ta.',
    1272: 'V-vâng, thưa ngài! Xin mời mọi người cứ tự nhiên đi qua...',
    1273: 'Ta thành thật xin lỗi vì đã cuốn các cháu vào hoàn cảnh trớ trêu này...',
    1274: 'Nhưng dù bằng bất cứ giá nào cũng phải ngăn chặn con trai ta lại.',
    1275: 'Ta vốn không ở vị thế để có thể thỉnh cầu các cháu,\nnhưng xin hãy... cho ta mượn sức mạnh của các cháu.',
    1276: 'Cứ để đó cho chúng tôi!',
    1277: 'Không, xin cảm ơn.',
    1278: 'Tôi không biết chính xác tình hình ở đây là gì,\nnhưng chuyện đó cũng chẳng quan trọng.',
    1279: 'Chúng tôi phải cứu lại vật hiến tế...\nbằng bất cứ giá nào.',
    1280: 'Đó là mục tiêu duy nhất của chúng tôi.',
    1281: 'Tôi không biết liệu điều đó có đồng nghĩa với việc\nchúng tôi sẽ ngăn chặn con trai của ông hay không.',
    1282: 'Được rồi.',
    1283: 'Ta vẫn còn những việc cần phải làm...',
    1284: 'Xin các cháu... hãy cứu lấy vật hiến tế bằng mọi giá...',
    1285: 'Vậy ra đây là chiếc phi thuyền...',
    1286: 'Nhanh lên nào, chúng ta phải khẩn trương lên.\nTa rất lo lắng cho hai người họ đấy!',
    1287: 'Chuyện gì thế này? Tại sao lại có quái vật\nở bên trong tàu cơ chứ?',
    1288: 'Nghĩ lại thì, lúc nãy hắn có lảm nhảm gì đó\nvề một cuộc giao dịch đúng không?',
    1289: 'Xem ra Lãnh chúa <NAME=NPC_10060> chắc chắn\nđang mưu tính điều gì đó mờ ám rồi...',
    1290: 'Chết tiệt... Tên Lãnh chúa thành trì này\ncàng lúc càng lộ rõ vẻ đáng ngờ...',
    1291: 'Á! Thả tôi ra khỏi đây mau!',
    1292: '<NAME=CP_0005>!',
    1293: 'Xem ra thằng bé vẫn bình an...',
    1294: 'Đợi một chút! Bọn chị sẽ cứu em ra ngay bây giờ!',
    1295: 'Cảm ơn mọi người... Suýt chút nữa thì toi thật rồi!',
    1296: 'Chúng định dùng em làm vật trao đổi trong cuộc giao dịch của chúng đấy!',
    1297: 'Giao dịch gì cơ?',
    1298: 'Tôi cũng đã lờ mờ đoán ra chuyện đó rồi.',
    1299: 'Anh nhạy bén thật đấy,\n<NAME=CP_0001>.',
    1300: 'Hóa ra đó là lý do chúng cứ bám theo em suốt...',
    1301: 'Nếu không tình cờ gặp được mọi người,\nthì giờ này chắc em đã...',
    1302: 'Nếu chúng thường xuyên giao nộp một số lượng con người nhất định cho lũ quái vật...',
    1303: 'Thì chúng sẽ không tấn công Floneia...\nđó chính là thỏa thuận giao dịch.',
    1304: 'Vậy ý em là quái vật có thể bị kiểm soát sao?',
    1305: 'Cuộc giao dịch đó là với ai chứ?\nLàm sao chuyện như vậy lại có thể xảy ra được...?',
    1306: 'Em xin lỗi, em cũng không biết chi tiết cụ thể...',
    1307: 'Không sao, chừng đó thông tin là quá đủ rồi. Cái tên Lãnh chúa khốn kiếp đó...\ndám lạm quyền làm ra những chuyện đồi bại thế này...',
    1308: 'Dù sao thì, <NAME=CP_0002> đang ở đâu rồi?',
    1309: 'Chẳng phải em ấy ở cùng với em sao?',
    1310: 'Dạ không, hình như Lãnh chúa <NAME=NPC_10060> đã đưa chị ấy đi riêng rẽ rồi ạ.',
    1311: 'Khốn thật! Chắc hẳn chúng ta đã đi lệch đường với họ lúc tới đây rồi...',
    1312: 'Nhanh lên, chúng ta phải đi tìm họ ngay!',
    1313: '<NAME=CP_0002>!',
    1314: 'A, các ngươi đến nhanh hơn ta tưởng đấy.\nCó lẽ ta đã đánh giá các ngươi quá thấp rồi...',
    1315: 'Đứng yên đó... Nếu các ngươi còn coi trọng tính mạng của vật hiến tế,\nta khuyên các ngươi không nên bước thêm một bước nào nữa.',
    1316: 'Dừng lại đi, con trai của ta...\nTrước khi mọi chuyện trở nên quá muộn.',
    1317: 'Quá muộn sao?',
    1318: 'Chính xác là quá muộn cho cái gì chứ?\nNgười sai ở đây chính là cha đấy, thưa Cha!',
    1319: 'Chẳng có cách nào biết được liệu chuyến hành hương hiến tế\nsẽ thành công hay chuốc lấy thất bại...',
    1320: 'Vậy mà cha lại bắt con phải đặt cược số phận của muôn dân\nvào một thứ mông lung bất định như thế sao?',
    1321: 'Thật là nực cười vô lý!',
    1322: 'Bất kỳ một lãnh chúa có trách nhiệm nào cũng sẽ tìm kiếm một phương cách đáng tin cậy hơn để bảo vệ thần dân của mình!',
    1323: 'Và ngài nghĩ rằng bắt tay thỏa thuận với quái vật\nlà một phương cách đáng tin cậy để bảo vệ người dân sao?',
    1324: 'Nó đáng tin cậy hơn nhiều so với một mạng sống vật tế ít ỏi!',
    1325: 'Ta từ chối trông cậy vào những phương pháp mơ hồ vô định đó.\nĐó chính là bổn phận của một lãnh chúa!',
    1326: 'Ngài có thực sự hiểu bản thân mình đang làm cái gì không đấy?',
    1327: 'Ta đang bảo vệ người dân của ta!\nLương tâm của ta hoàn toàn trong sạch!',
    1328: 'Thì ra đó là lý do tại sao <NAME=MA_0012_01>\nlại được lập ra...',
    1329: 'Không phải bất kỳ ai cũng có thể làm vật trao đổi thích hợp được đâu...\nNhưng hôm nay, ta lại có một lựa chọn vô cùng tuyệt hảo!',
    1330: 'Cùng với các ngươi, còn có một cặp mẹ con vừa mới đặt chân tới ngôi làng...',
    1331: 'Không lẽ... người phụ nữ cùng cô bé con mà chúng ta thấy lúc trước!?',
    1332: 'Các ngươi nên học tập họ thì hơn...',
    1333: 'Ta chỉ bảo rằng ta có một sứ mệnh cao cả giao phó cho họ,\nvà họ đã hăng hái đi theo ta ngay!',
    1334: 'Mặc dù, tất nhiên là ta chưa hề nói cho họ biết đích xác\nnơi họ sẽ đến là đâu rồi...',
    1335: '......',
    1336: 'Nhưng ta rất biết ơn họ...\nNhờ họ mà muôn dân của ta sẽ được cứu rỗi.',
    1337: 'Ngươi đem con người ra làm vật trao đổi giao dịch...\nmà ngươi còn mở mồm ra nói về chuyện cứu người sao!?',
    1338: 'Chính xác là như thế đấy! Ta có toàn quyền để nói như vậy!',
    1339: 'Khốn nạn... Đừng hòng nói lý lẽ với loại người như ngươi nữa!',
    1340: 'Đừng có sốt ruột... Tất cả các ngươi cũng sẽ cùng đi thôi!',
    1341: '<NAME=NPC_10080>! Đến giờ khởi hành rồi!\nKhởi động phi thuyền ngay!',
    1342: 'Ngươi nghĩ ta sẽ giúp đỡ một kẻ như ngươi sao?\nKhông bao giờ có chuyện đó đâu!',
    1343: 'Lũ ngu xuẩn! Đồ đần độn! Quân khốn nạn!\nTại sao các ngươi không chịu tuân theo mệnh lệnh của ta hả!?',
    1344: 'Được lắm... Nếu ngươi không chịu lái tàu,\nthì đích thân ta sẽ tự mình lái!',
    1345: 'Này! Dừng lại ngay! Đừng có chạm vào đó!\nNgươi không biết mình đang làm cái gì đâu!',
    1346: 'Hừ! Bất kỳ việc gì một kẻ tầm thường như NGƯƠI làm được,\nta đều có thể làm được tốt hơn!',
    1347: 'Mọi chuyện không đơn giản như thế đâu...\nThôi mà, dừng lại đi! Ta cầu xin ngươi đấy được chưa?',
    1348: 'Này! Ta bảo dừng lại cơ mà! Ngươi không thể đột ngột\nbơm một lượng ma lực khổng lồ vào như thế được đâu!',
    1349: 'Hừ! Thấy chưa? Ta hoàn toàn có thể điều khiển thiết bị pháp thạch một cách hoàn hảo--',
    1350: 'Ta đã bảo rồi mà! Á... Quả này nguy to rồi!',
    1351: 'Pháp thạch đang mất kiểm soát rồi!\nCứ đà này thì nó sẽ...',
    1352: 'Nó sẽ bị làm sao?',
    1353: '...Nổ tung.',
    1354: 'Tệ nhất là toàn bộ khu vực này sẽ bị thổi bay thành tro bụi...',
    1355: 'Ông nói cái gì cơ!?\nKhông thể dừng nó lại được sao?',
    1356: 'Không còn đủ thời gian cho việc đó nữa rồi! Tất cả những gì chúng ta có thể làm lúc này là cố gắng giảm thiểu thiệt hại nhiều nhất có thể thôi...',
    1357: 'Vậy chúng ta phải làm thế nào?',
    1358: 'Cách duy nhất là phải phá hủy thiết bị đó trước khi pháp thạch vượt quá giới hạn cực điểm.',
    1359: 'KHÔNG! Ta không cho phép các ngươi làm thế! Con tàu này phải bay!\nTa phải cứu lấy người dân của ta!',
    1360: 'Có cái gì đó đang lao về hướng này!',
    1361: 'Lại là hắn... ngay vào đúng cái lúc này cơ chứ!',
    1362: 'Ta đã tìm thấy ngươi rồi... vật hiến tế...\nLần này, ngươi sẽ không thoát được đâu...',
    1363: 'Ngươi là ai?\nNgươi đến đây để cứu ta đấy phải không?',
    1364: 'May mắn thật đấy... T-tốt lắm!\nHãy tiêu diệt hết bọn chúng cho ta!',
    1365: 'Ta sẽ phải tính toán lại kế hoạch... Chỉ cần ta đem theo được vật hiến tế này đi cùng...',
    1366: 'Cô ta là con mồi của ta...',
    1367: 'C-cái gì cơ?',
    1368: 'Biến đi...',
    1369: 'Con trai!',
    1370: 'Ngươi rốt cuộc là kẻ nào!?',
    1371: 'Tại sao ngươi cứ nhắm vào tấn công chúng tôi!?',
    1372: 'Các ngươi không cần phải biết điều đó...',
    1373: 'N-này! Giờ không phải lúc cho chuyện đó đâu!\nCác người mau phá hủy thiết bị pháp thạch đi!',
    1374: 'Biết rồi, chúng tôi biết rồi!',
    1375: 'Mọi người xin hãy lùi lại phía sau!',
    1376: '?',
    1377: 'Xem ra chúng ta đã ngăn chặn được vụ nổ...\nbằng cách nào đó...',
    1378: 'Cha...\nTại sao cha lại đỡ đòn cho con...?',
    1379: 'Lỗi lầm... là ở cha... vì đã không thể...\nngăn con lại sớm hơn...',
    1380: 'Cha... sẽ lấy mạng sống của mình... để chuộc tội...\ncho những cái chết mà cha đã gây ra...',
    1381: 'C-cha ơi...',
    1382: 'Con... phải sống tiếp... và ăn năn chuộc lại... những lỗi lầm\ncủa mình...',
    1383: 'Một lãnh chúa... phải luôn kiên cường... Tuyệt đối không bao giờ... được chọn... con đường dễ dàng...',
    1384: 'Con phải luôn kiên định... Tuyệt đối không được cúi đầu... trước lũ quái vật...',
    1385: 'Sinh mạng của... muôn dân... là điều trân quý... nhất trên đời...',
    1386: 'Con trai của cha...',
    1387: '...',
    1388: 'C-cha ơi...\nCon... Con...',
    1389: 'Các bạn là...',
    1390: 'Chính ông cụ ấy đã cứu hai mẹ con cháu đấy!',
    1391: 'Cha...',
    1392: '...<NAME=CP_0002>!',
    1393: 'Vết thương này...',
    1394: 'Khi viên pháp thạch phát nổ,\n<NAME=CP_0002> đã lao ra đỡ đòn cho em...',
    1395: 'Cô ấy đã hứng trọn toàn bộ sức mạnh của pháp thạch ở cự ly quá gần...\nĐiều đó đang làm tổn hại đến các chức năng cơ thể của cô ấy...',
    1396: 'Nó không đe dọa đến tính mạng, nhưng phép thuật trị thương bình thường không thể chữa lành được...',
    1397: '......',
    1398: '...Được rồi. Đi thôi.',
    1399: 'Đi đâu cơ?',
    1400: 'Nếu chúng ta đến ngôi làng của em,\nem chắc chắn mọi người ở đó sẽ có cách chữa khỏi cho chị ấy.',
    1401: 'Thật sao!?',
    1402: 'Em vốn không muốn quay trở về đó trước khi đặt chân tới <NAME=MA_0041_01>...',
    1403: 'Nhưng giờ không phải là lúc để bận tâm về chuyện đó nữa.',
    1404: 'Nào, chúng ta hãy đến ngôi làng của em đi.',
    1405: 'Có một lối vào nằm bên trong <NAME=MA_0013_01>.\nEm sẽ dẫn đường cho mọi người.'
}
