import os
import glob

def main():
    managed = r"d:\Viet Hoa Game\I am Setsuna\SETSUNA_Data\Managed"
    for dll in glob.glob(os.path.join(managed, "*.dll")):
        with open(dll, "rb") as f:
            c = f.read()
            if b"_AutoGeneratedTranslations" in c:
                print(f"Found in {os.path.basename(dll)}")
            if b"SetsunaTranslator" in c:
                print(f"SetsunaTranslator found in {os.path.basename(dll)}")

if __name__ == "__main__":
    main()
