# Translation batch 1 for Nive Island (RIDs 5265 to 5325)
NIVE_TRANS_1 = {
    5265: "Hiếm khi mới có người từ đại lục tới đây.\nThường thì người ta chỉ rời đi thôi...\n|\nHôm nay sắp có lễ khởi hành đấy.\n|\nHả? Ai khởi hành á?\nVật hiến tế chứ ai nữa!",
    5266: "Có chuyện gì thế? Nếu anh tìm chuyến phà vừa rồi,\nnó đã nhổ neo quay về đại lục rồi.\n|\nDù sao anh cũng đã cất công tới tận đây,\nviệc gì phải vội vàng quay về chứ.\n|\nÍt nhất hãy nán lại xem lễ khởi hành đã.\nDù nó cũng chẳng có gì rộn ràng cho lắm...",
    5267: "Khoan đã nào... Không đi thuyền\nthì làm sao các người quay lại đây được!?\n|\nCái gì? Bằng phi thuyền á!?\nĐùa tôi đấy à...",
    5268: "Muốn đến làng hả?\n|\nRời khỏi cảng này, cứ đi về hướng tây bắc\nlà sẽ thấy ngôi làng ngay thôi...",
    5269: "Tiếc là sẽ không có chuyến phà nào nữa đâu...\n|\nChuyến tàu tiếp theo cập bến\nsẽ là để đón vật hiến tế đi đấy.",
    5270: "Ra anh là lính đánh thuê à.\nNhờ anh chăm sóc cho bé <NAME=CP_0002> nhà chúng tôi nhé!",
    5271: "H-hả!? <NAME=CP_0002>!?\nSao cháu lại ở đây!?",
    5272: "Dạo này ma thú hoành hành nên hiếm ai\nlặn lội tới hòn đảo này lắm...\n|\nAnh thật dũng cảm khi tới đây.\nThay mặt dân làng, xin nhiệt liệt chào đón anh!",
    5273: "Chuyến phà tiếp theo tới đây\nsẽ đưa mọi người tới thành trì Floneia.\n|\nĐoàn hộ tống vật hiến tế luôn tới đó trước\nđể quyết định lộ trình cho chuyến đi.\n|\nĐường bộ... đường biển... đường hàng không...\nTừ Floneia, mọi người sẽ chọn ra lộ trình an toàn nhất.",
    5274: "Chẳng ngờ cũng có ngày chúng ta phải tiễn\nbé <NAME=CP_0002> đi như thế này...\n|\nCảm ơn cháu...\nCảm ơn cháu rất nhiều...",
    5275: "Đ-đúng là cháu thật rồi,\n<NAME=CP_0002>, phải không!?",
    5276: "Kính chào quý khách!",
    5277: "Aha! Anh có công thức nấu ăn kìa.\n|\nNếu đưa cho tôi, tôi có thể thêm món đó\nvào thực đơn của quán đấy!",
    5278: "Đưa công thức",
    5279: "Không đưa công thức",
    5280: "Để xem nào, chúng ta có món gì ở đây...\n|\nRa là thế... Được đấy...\nMón này tôi nấu ngon lành, không thành vấn đề!\n|\nTôi đã thêm vào thực đơn rồi, cứ gọi món\nbất cứ lúc nào anh muốn nhé!\n|\nNào, quay lại làm việc thôi...",
    5281: "Thế à? Tiếc quá nhỉ...\nKhi nào đổi ý thì cứ bảo tôi nhé.\n|\nNào, quay lại làm việc thôi...",
    5282: "Xin lỗi, quán vẫn chưa mở cửa.",
    5283: "Ủa? Anh từ đâu tới thế?\nAnh đâu có ở trên chuyến phà vừa cập bến nhỉ?",
    5284: "Muốn đến làng hả?\n|\nRời khỏi cảng này, cứ đi về hướng tây bắc\nlà sẽ thấy ngôi làng ngay thôi!",
    5285: "Dù có trải qua bao nhiêu lần đi nữa,\nviệc tiễn đưa vật hiến tế chẳng bao giờ dễ dàng...\n|\nNhưng có lẽ đây sẽ là lần cuối cùng của tôi rồi.\nDù sao thì tôi cũng già cả rồi mà...",
    5286: "Xin lỗi nhé, quán vẫn đang chuẩn bị mở cửa.\nTôi vừa mới thuê được chỗ này thôi.\n|\nTôi luôn mơ ước mở một quán rượu của riêng mình...\nCứ chờ xem, nơi này sẽ sớm đông nghẹt khách cho coi.",
    5287: "Lễ khởi hành của vật hiến tế sắp sửa bắt đầu.\n|\nCon gái tôi... chính là người sẽ gánh vác trọng trách lớn lao ấy...\n|\nCó lẽ đây cũng chính là định mệnh...",
    5288: "Cậu có được tự do ngày hôm nay là nhờ <NAME=CP_0002>.\n|\nXin cậu... ngàn vạn lần đừng bao giờ quên điều đó...",
    5289: "Cuối cùng cũng tới lễ khởi hành của <NAME=CP_0002> rồi sao...\n|\nNgày mẹ con bé là <NAME=NPC_10150> lên đường,\nta chưa từng dám nghĩ ngày này lại đến...",
    5290: "<NAME=CP_0001>... <NAME=CP_0003>...\n|\nXin hãy chăm sóc cho con gái ta... <NAME=CP_0002>...",
    5291: "Chẳng ngờ ta lại được gặp lại <NAME=CP_0002>...\nLiệu đây có phải là mơ không...",
    5292: "Mẹ con bé, rồi cả người dì nữa...\n|\nTôi cũng từng tiễn họ đi y hệt như thế này...\nChúng tôi bất lực, chẳng làm được gì hơn...\n|\nDẫu biết là vì sự bình yên của tất cả,\nnhưng một gia đình phải gánh chịu chừng ấy đau thương thì thật quá tàn nhẫn...",
    5293: "Vẫn còn một khoảng thời gian trước lễ khởi hành,\ncứ thong thả mà suy nghĩ cho kỹ nhé.",
    5294: "A... Thật thuần khiết và cao quý...\nCon bé giống hệt người mẹ <NAME=NPC_10150> thuở nào.\n|\nTa tin chắc <NAME=NPC_10150> vẫn đang dõi theo con bé.\n|\nHy vọng của muôn dân đều đặt vào <NAME=CP_0002>.\nXin hãy trông nom con bé thật chu đáo nhé.",
    5295: "Mọi người đã trở về... lại còn trên một phi thuyền hoàng gia nữa!\nTa thật sự ngỡ ngàng đấy!\n|\nLý do là gì cũng chẳng quan trọng.\nĐược gặp lại các cháu là ta vui lắm rồi!",
    5296: "Cả mẹ lẫn con gái đều phải lên đường làm vật hiến tế.\nSố phận thật trớ trêu làm sao...\n|\nÍt nhất ta cũng phải nấu cho con bé một bát súp rau rừng tuyết mà nó thích nhất mới được...",
    5297: "Ta chẳng cần biết ngươi là ai, nhưng cấm ngươi động vào <NAME=CP_0002> đấy nhé.\n|\nCon bé có một sứ mệnh vô cùng trọng đại cần phải hoàn thành.",
    5298: "Mẹ của <NAME=CP_0002> là <NAME=NPC_10150> cũng từng sở hữu ma lực kinh người.\n|\nTa sẽ cầu nguyện để linh hồn của <NAME=NPC_10150> luôn che chở và dẫn lối cho con bé...",
    5299: "<NAME=CP_0002> ơi...\n|\nĐể bà ngắm nhìn cháu thật kỹ lần cuối nào...\n|\nTrời ơi... Trời đất ơi...\nĐôi mắt già nua này lại không cầm được nước mắt rồi...",
    5300: "Ôi trời đất ơi! Bà chẳng dám nghĩ là sẽ được gặp lại cháu, <NAME=CP_0002>!\n|\nBiết cháu về thì bà đã nấu sẵn nồi súp rau rừng tuyết rồi!",
    5301: "Cô bé được chọn làm vật hiến tế là một thiếu nữ vô cùng tốt bụng...\n|\nCon bé thường tới <NAME=MA_0006_01> để cầu nguyện cho các vật hiến tế đời trước.\n|\n<NAME=MA_0006_01> ở đâu ư?\nCứ băng qua <NAME=MA_0005_01> là tới nơi thôi.",
    5302: "Lại đi xin trưởng làng tha mạng cho chính kẻ toan ám sát mình...\n|\n<NAME=CP_0002> quả thực quá đỗi nhân hậu...",
    5303: "Hy vọng của muôn dân đều đặt vào vật hiến tế.\n|\n<NAME=CP_0002> nhất định sẽ hoàn thành sứ mệnh của mình. Tôi tin chắc con bé làm được...",
    5304: "Cháu đừng bận lòng về cha cháu nhé.\n|\nTa sẽ bảo chồng ta thường xuyên qua lại chăm nom cho ông ấy!",
    5305: "Mọi người đã đi tới tận <NAME=MA_0041_01> rồi quay về đây ư...?\n|\nV-vậy còn nghi thức thì sao...?",
    5306: "Gia đình tôi rất thân thiết với nhà của cô bé được chọn làm vật hiến tế...\n|\nVậy là ngày này cuối cùng cũng tới rồi ư...? *Thở dài*",
    5307: "Ma thú tấn công ngày càng thường xuyên hơn.\n|\nCứ đà này thì chẳng biết ngôi làng sẽ ra sao nữa...",
    5308: "Tôi cũng chẳng rõ <NAME=MA_0041_01> là nơi như thế nào.\n|\nThực ra ngay cả những hộ vệ từng trở về cũng hầu như chẳng nhớ được gì nhiều.\n|\nNgười ta còn đồn rằng ký ức của họ đã bị xóa sạch...",
    5309: "Xem ra đêm nay tôi phải uống rượu thâu đêm với <NAME=NPC_10010> rồi...\n|\nBảo trọng nhé, <NAME=CP_0002>...",
    5310: "Tôi vẫn chưa dám tin vào mắt mình nữa!\nVật hiến tế lại cưỡi phi thuyền bay về đây... Đúng là chuyện không tưởng!",
    5311: "Này này, anh đã đến <NAME=MA_0006_01> bao giờ chưa?\n|\nNghe nói cứ đi xuyên qua <NAME=MA_0005_01> cạnh làng là tới...\n|\nNhưng trong rừng có ma thú nguy hiểm lắm nên em chưa từng dám bén mảng tới.",
    5312: "Chị <NAME=CP_0002> trông xinh đẹp quá chừng...\n|\nSau này lớn lên, ước gì em cũng xinh đẹp được như chị ấy!",
    5313: "Đường tới <NAME=MA_0041_01> có xa lắm không ạ?\nNếu không quá xa thì em cũng muốn đi cùng...",
    5314: "Liệu có ngày nào đó em cũng được chọn làm vật hiến tế không nhỉ...\n|\nNếu em được chọn làm vật hiến tế, liệu cha em có vui lòng không anh?",
    5315: "Cho em đi phi thuyền với, cho em đi với!",
    5316: "Nàng vừa hiền dịu, vừa xinh đẹp, hoàn hảo không chút tì vết!\n|\nChính vì thế nàng mới sinh ra để dành cho tôi chứ.\n|\nNhưng giờ nàng đã được chọn làm vật hiến tế rồi, chắc tôi đành phải học cách quên nàng đi thôi...",
    5317: "A... Giá mà tôi dũng cảm và mạnh mẽ hơn...\n|\nTôi sẽ quét sạch lũ ma thú trong chớp mắt! Sẽ thành người hùng ngay trong đêm!\n|\nThôi thì... người vừa đẹp trai lại vừa cái thế anh hùng đâu có dễ sinh ra trên đời...",
    5318: "<NAME=CP_0003> bỗng dưng xuất hiện ở làng rồi xung phong vào đội hộ tống...\n|\nNói nhỏ này thôi nhé, tôi chắc mẩm là nàng đang để ý tôi đấy.\n|\nBiết đâu nàng định tỏ tình với tôi trước khi lên đường cũng nên...",
    5319: "Ôi số phận nghiệt ngã! Trái tim si tình này biết trao trọn cho ai đây?\n|\nGiá như trong làng có ai đó ma lực mạnh hơn <NAME=CP_0002>!\n|\nThì nàng đâu phải rời đi... Nàng đã có thể hạnh phúc sống trọn đời bên tôi trong ngôi làng này rồi...",
    5320: "Tôi vừa mới quyết định trao gửi trái tim cho người khác... thì nàng lại xuất hiện trước mặt tôi một lần nữa!?\n|\nÔi, <NAME=CP_0002> hỡi...\nNàng đúng là người phụ nữ tàn nhẫn gieo rắc tương tư mà...",
    5321: "Đây là Nive, một trong những ngôi làng nằm ở cực bắc của thế giới này.\n|\nHiện tại mọi người đang bận rộn chuẩn bị cho lễ khởi hành của vật hiến tế.",
    5322: "Anh mạnh mẽ thật đấy!\nCon ma thú đó to lớn đến thế cơ mà!\n|\nAnh hoàn toàn có thể bỏ chạy, nhưng không... anh đã ở lại chiến đấu. Tôi hoàn toàn tin tưởng anh!",
    5323: "Cậu đi đâu thế? Lén rời khỏi làng à?\n|\nMà thôi, không sao. Nếu còn điều gì muốn làm trước khi rời đi thì cậu cứ làm cho thỏa lòng nhé.",
    5324: "<NAME=CP_0002> thường hay chơi đùa với thằng nhóc nhà tôi lắm.\n|\nCon bé đi rồi tôi sẽ nhớ nó lắm đây...",
    5325: "Mừng mọi người trở về...\n|\nNói là \"trở về\" thì có hơi lạ lùng, nhưng tôi chẳng biết nói gì hơn nữa..."
}
