# Translation batch 2 for Nive Island (RIDs 5326 to 5387)
NIVE_TRANS_2 = {
    5326: "Em không nói cho ai biết chị <NAME=CP_0002> đi đâu đâu...\nEm đã hứa giữ bí mật rồi!\n|\nNhưng khi nào chị ấy từ Bia Tưởng Niệm Tuyết Rơi trở về thì em sẽ nói cho anh biết...",
    5327: "Bố em là lính gác cổng làng, bố đã giúp mọi người sơ tán an toàn đấy!\n|\nBố em tuyệt vời lắm luôn...",
    5328: "Vật hiến tế là làm gì thế anh?\n|\nEm chỉ mong chị ấy sớm trở về nhà thôi...",
    5329: "Bố em ngày nào cũng tuần tra lối vào để bảo vệ cả làng.\n|\nSau này lớn lên và mạnh mẽ rồi, em cũng sẽ bảo vệ làng y như bố em!",
    5330: "Oaーーー! Mọi người đã trở về thật rồi!",
    5331: "Dạo gần đây ma thú trở nên hung hãn hơn hẳn.\n|\nNgay cả việc băng qua <NAME=MA_0005_01> ở phía đông bắc dạo này cũng trầy trật lắm...",
    5332: "Xin lỗi nhé, lúc đó tôi mải lo sơ tán dân làng nên chẳng kịp giúp anh...\n|\nNhưng anh mạnh thế kia thì chắc cũng chẳng hề hấn gì đâu nhỉ? Đúng không?",
    5333: "Lễ khởi hành sắp sửa bắt đầu rồi.\nCậu đã chuẩn bị sẵn sàng chưa?",
    5334: "Tôi mong mọi người tới được <NAME=MA_0041_01> trước khi lũ ma thú sinh sôi nhiều hơn nữa...\n|\nNghe có vẻ ích kỷ, nhưng đó thực sự là vì sự sống còn của tất cả chúng ta...",
    5335: "Mọi người có đến được <NAME=MA_0041_01> không đấy?\nKhông lẽ có trục trặc gì xảy ra rồi sao?",
    5336: "Lễ khởi hành của vật hiến tế sắp sửa bắt đầu rồi.\n|\nMột chuyến đi dâng hiến sinh mạng để xoa dịu lũ ma thú hung bạo...\n|\nĐó là phong tục lâu đời được lưu truyền trong ngôi làng này.",
    5337: "Nhờ có <NAME=CP_0002> mà mọi người mới có thể an cư mà không phải nơm nớp sợ hãi.\n|\nChúng ta tuyệt đối không bao giờ được phép quên điều đó...",
    5338: "Bao đời nay, người được chọn làm vật hiến tế đều là phụ nữ.\n|\nChỉ những ai sở hữu ma lực dồi dào mới đủ tư cách trở thành vật hiến tế.\n|\nCó lẽ tư chất ấy vốn thuộc về phụ nữ, những người mang thiên chức khai sinh mầm sống mới...",
    5339: "<NAME=CP_0002> ơi...\nEm là niềm tự hào của cả ngôi làng này...\n|\nMỗi khi tuyết rơi, chị lại nhớ về em...",
    5340: "<NAME=CP_0002>, em và những người bạn đồng hành quả thực rất đặc biệt.\n|\nThật kỳ lạ... Dường như từ đầu chị đã có cảm giác đó rồi...",
    5341: "Em chẳng sợ lạnh tí nào đâu!\n|\nMột ngày nào đó, em sẽ đủ mạnh mẽ để bảo vệ người khác! Giống như chị gái trong đội hộ tống ấy!",
    5342: "Ma thú đáng sợ thật anh nhỉ...\n|\nNhưng chúng ta không thể chịu thua được! Phải chiến đấu! Em cũng sẽ chiến đấu!\n|\nMà công nhận chúng nó đáng sợ thật đấy...",
    5343: "Em không muốn phải nói lời tạm biệt với chị <NAME=CP_0002> đâu...\n|\nHay là em bảo chị ấy đừng đi nhỉ... Em sẽ bảo là EM sẽ bảo vệ ngôi làng này!",
    5344: "Nói câu \"bảo trọng nhé\" nghe có kỳ cục không anh?\n|\nCơ mà em không muốn nói tạm biệt đâu... Nghe \"bảo trọng nhé\" hay hơn nhiều...\n|\nNên là... chị bảo trọng nhé!",
    5345: "Oaーーー, chị <NAME=CP_0002> đã về rồi!\nChị vẫn bình an vô sự, em mừng quá đi mấtーーー!",
    5346: "Con bé lo chuyện bao đồng đó lại bảo nó lo cho TÔI cơ đấy!\n|\nVật hiến tế lo thân mình còn chưa xong mà còn đi lo cho người khác!",
    5347: "Giờ con bé bao đồng đó lại đi cứu giúp một tên sát nhân kìa!\n|\nBộ con bé nghĩ mình là thánh nhân chắc!?",
    5348: "Con bé bao đồng đó VẪN còn lượn lờ ở đây à? Hứ!\n|\nTrông ngứa mắt chết đi được! Sao nó không biến cho nhanh đi nhỉ? Đi khuất mắt cho tôi nhờ!",
    5349: "Đến nước này rồi mà còn mở miệng nói chuyện với TÔI làm gì!?\n|\nKệ xác tôi đi, lo cho bản thân mình trước đi!\n|\nĐể tôi yên một mình... Xin cô đấy...",
    5350: "Sao hả? Cất công quay về tận đây chỉ để phí thời giờ nói chuyện với TÔI đấy à?\n|\nVẫn cái tính bao đồng... *sụt sịt*... không bao giờ đổi... *hức, hức*...",
    5351: "Hôm nay là ngày lành để vật hiến tế lên đường.\n|\nNó làm lão nhớ lại cái ngày lão tiễn vợ mình đi năm xưa... *Thở dài*",
    5352: "Chị gái của vợ lão được chọn làm vật hiến tế, thế là bà ấy xin vào đoàn hộ tống...\n|\nRồi bà ấy chẳng bao giờ quay về nữa.\n|\nKhông đi cùng bà ấy là sai lầm lớn nhất đời lão... Ngày nào lão cũng phải sống trong ân hận...",
    5353: "Được rồi, lão quyết định rồi! Lão sẽ gia nhập đoàn hộ tống của <NAME=CP_0002>!\n|\n...Cơ mà vừa nói thế với thằng cháu thì nó đã gạt đi, bảo lão già quá rồi...",
    5354: "Đến đợt vật hiến tế tiếp theo, lão nhất định sẽ tham gia đoàn hộ tống!\n|\n...Đó là nếu lão còn sống được đến lúc đó.",
    5355: "Giá mà lão có thể bay lượn trên bầu trời như các cháu... *Thở dài*\n|\nNếu làm được thế, lão tin chắc mình sẽ gặp lại được bà nhà... Chẳng hiểu sao lão lại có linh cảm như vậy...",
    5356: "Sau khi sinh ra bố tôi, bà nội tôi đã lên đường làm hộ vệ cho vật hiến tế.\n|\nGià hay trẻ, nam hay nữ...\nChỉ cần có bản lĩnh thì bất kỳ ai cũng có thể gia nhập đội hộ tống.",
    5357: "Nghe những câu chuyện thời làm hộ vệ của bà nội đã thôi thúc tôi bắt đầu nghiên cứu về ma thú...\n|\nChẳng phải ma thú chính là lý do duy nhất khiến chúng ta phải liên tục cống nạp vật hiến tế sao?",
    5358: "Nếu việc hiến tế có thể xoa dịu được ma thú...\n|\nThì ắt hẳn cũng phải có cách nào đó để khiến chúng nguôi ngoai vĩnh viễn chứ, đúng không?",
    5359: "Tôi nghe nói trên đại lục có vô số ma thú mạnh ngoài sức tưởng tượng của chúng ta.\n|\nXin hãy cẩn trọng trên suốt chặng đường. Đó chắc chắn không phải chuyến đi dễ dàng đâu...",
    5360: "Tôi chưa từng nghe chuyện vật hiến tế tới được <NAME=MA_0041_01> rồi lại quay trở về bao giờ...\n|\nCó lẽ thời thế thực sự đang bắt đầu đổi thay rồi...",
    5361: "Trước đây chúng tôi luôn nghĩ ma thú đều từ đại lục tràn sang... nhưng giờ không còn như vậy nữa.\n|\nChúng cứ như từ hư không chui ra... và số lượng ngày một đông thêm...",
    5362: "Vừa rồi nhờ có ba người mà mọi người mới thoát nạn...\n|\nNhưng nếu chuyện tương tự lại xảy ra lần nữa, chúng tôi sẽ chẳng có cơ may nào chống đỡ nổi đâu!",
    5363: "Vậy anh cũng sẽ gia nhập đoàn hộ tống vật hiến tế chứ?\n|\nCó một người đàn ông mạnh mẽ như anh đi cùng chắc chắn sẽ nâng cao cơ hội thành công!",
    5364: "Chỉ có mọi người mới xoa dịu được lũ ma thú. Tôi luôn cầu nguyện cho chuyến đi của các bạn được bình an!",
    5365: "Xem ra chuyến đi của mọi người vẫn chưa kết thúc nhỉ...\n|\nDù sao thấy mọi người bình an vô sự là mừng rồi.",
    5366: "Trong lúc phiêu bạt, tôi ghé qua ngôi làng này và thấy rất mến nơi đây.\n|\nRốt cuộc tôi ở lại luôn... nhưng dân làng vẫn còn xa cách với tôi lắm...\n|\nƯớc gì có cách nào đó để giành được lòng tin của họ nhỉ...",
    5367: "Có khi ở lại đây quá nguy hiểm rồi chăng...\n|\nKhông, không! Mình nói gì thế này!?\nNơi này là quê hương thứ hai của mình,\nmình nhất định phải ở lại bảo vệ nó!",
    5368: "Tôi ở hòn đảo này cũng được một thời gian rồi, nhưng đây là lần đầu tiên tôi thấy lễ khởi hành.\n|\nQuả thực rất... nghẹn ngào. Ngay cả một kẻ ngoại tộc như tôi cũng thấy thắt lòng...",
    5369: "Vật hiến tế quả thực rất khác biệt so với người thường nhỉ?\n|\nKhông chỉ bởi ma lực cao cường... mà ở cô ấy toát lên một khí chất gì đó thật đặc biệt...\n|\nTôi thật lòng cầu chúc chuyến đi của mọi người sẽ thành công...",
    5370: "Được tự do bay lượn trên bầu trời bằng phi thuyền như cánh chim...\n|\nOa! Mới nghĩ đến thôi mà tôi đã thấy phấn khích tột độ rồi!\n|\nMọi người đang có một hành trình phi thường thật đấy...",
    5371: "Kính chào quý khách!",
    5372: "Đã cất công tới đây rồi, xin mời cứ thong thả xem đồ nhé.",
    5373: "Tôi chẳng ngờ hôm nay lại có khách ghé qua đấy!",
    5374: "Thực ra tôi vừa dọn dẹp xong sau lễ khởi hành của vật hiến tế.\n|\nCon bé thực sự trông rất đẹp... Cô ấy nhất định sẽ làm được. Tôi tin chắc thế.\n|\nGiờ tôi cũng phải hoàn thành sứ mệnh của mình. Tôi được giao phó một trọng trách vô cùng quan trọng...",
    5375: "Mẹ phải ra đi bỏ lại chị ấy, tội nghiệp chị ấy quá.\n|\nĐược rồi! Đã thế thì em sẽ phải đứng ra bảo vệ chị ấy mới được!",
    5376: "Mấy nay bận rộn chuẩn bị cho lễ khởi hành quá...\nGiờ tôi chỉ muốn được nghỉ ngơi một giấc thật đã thôi.",
    5377: "Lần này tôi lại không được chọn làm vật hiến tế rồi...\n|\nBiết đâu lần tới sẽ tới lượt tôi cũng nên. Tôi phải giữ gìn sức khỏe cho thật tốt phòng khi tới lượt...",
    5378: "Nếu anh tới xem lễ khởi hành thì vừa mới kết thúc rồi.\n|\nMột chuyến đi dâng hiến sinh mạng để xoa dịu ma thú... Đó là phong tục cổ xưa của chúng tôi.",
    5379: "Con bé bao đồng đó lại bảo nó lo cho TÔI cơ đấy!\n|\nLúc nào cũng chỉ biết lo cho người khác thay vì... *sụt sịt*... bản thân mình... *hức, hức*...",
    5380: "Ma thú vốn từ đại lục tràn sang đây. Dạo này số lượng cũng tăng lên nhiều.\n|\nTôi nghĩ chúng ta đã tiễn vật hiến tế lên đường vừa đúng lúc đấy...",
    5381: "Nghe mẹ kể chuyện ngày xưa... Hóa ra bà nội em cũng từng là hộ vệ cho vật hiến tế đấy!",
    5382: "Hôm nay là ngày lành!\nVật hiến tế đã thuận buồm xuôi gió lên đường.\n|\nLão lại nhớ về cái ngày lão tiễn vợ mình đi...",
    5383: "Tôi đã dặn lòng là phải mỉm cười tiễn cô ấy đi... nhưng không tài nào làm được...\n|\nDù sao thì sau ngày hôm nay tôi sẽ không khóc nữa. Tôi phải kiên cường... vì đứa con gái bé bỏng của cô ấy...",
    5384: "Gia đình tôi rất thân thiết với cô bé được chọn làm vật hiến tế, nên lòng thấy ngổn ngang lắm...\n|\nVẫn biết đó là niềm vinh dự tột cùng, nhưng mà...",
    5385: "Cả hai chị em gái, người này nối tiếp người kia đều bị chọn làm vật hiến tế...\n|\nDẫu biết là vì bình yên của muôn người, nhưng một gia đình phải chịu chừng ấy tang thương thì tàn nhẫn quá...\n|\nÍt nhất ta cũng phải bảo đảm cho đứa con gái bé bỏng của con bé có được một cuộc đời hạnh phúc...",
    5386: "Số phận đúng là trớ trêu...\nTôi chỉ biết cầu nguyện cho chuyến đi của họ được thuận buồm xuôi gió...\n|\nDân làng chúng ta phải cùng nhau chung tay nuôi nấng đứa bé đó nên người. Đó là điều tối thiểu chúng ta có thể làm...",
    5387: "Chúng ta buộc phải cống nạp vật hiến tế...\nChẳng còn sự lựa chọn nào khác cả.\n|\nTất cả những gì chúng ta có thể làm là tiếp tục sống và không bao giờ được quên món nợ ân tình này.\n|\nÝ tôi là, ngoài việc đó ra ta còn làm được gì nữa đây?"
}
