import openpyxl
import json

excel_path = "D:/Viet Hoa Game/I_am_Setsuna-parameter-Steam.xlsx"
wb = openpyxl.load_workbook(excel_path)

# =========================================================================
# 1. EnemySkillDataMessage (89 skills)
# =========================================================================
ws_es = wb["EnemySkillDataMessage"]
with open("D:/Viet Hoa Game/temp_scripts/EnemySkillDataMessage.json", "r", encoding="utf-8") as f:
    es_data = json.load(f)

es_dict = {
    "Test Attack": "Đòn Đánh Thử Nghiệm",
    "Regular Attack": "Đòn Đánh Thường",
    "Dive": "Lao Xuống",
    "Rocket Dive": "Lao Tên Lửa",
    "Slap": "Vả",
    "Bite": "Cắn",
    "Focus": "Tập Trung",
    "Swoop": "Sà Xuống",
    "Wingbeat": "Đập Cánh",
    "Flee": "Bỏ Chạy",
    "Blinding Gaze": "Ánh Nhìn Mù Lòa",
    "Petrifying Gaze": "Ánh Nhìn Hóa Đá",
    "Paralyzing Gaze": "Ánh Nhìn Tê Liệt",
    "Cure": "Trị Liệu",
    "Healing Feather": "Lông Vũ Trị Thương",
    "Whirlwind": "Lốc Xoáy",
    "Hurricane": "Cuồng Phong",
    "Glide Attack": "Lướt Tấn Công",
    "Shell Shield": "Mai Rùa Hộ Thuẫn",
    "Accumulate Power": "Tụ Lực",
    "Poison Claw": "Vuốt Độc",
    "Shell Boomerang": "Mai Rùa Boomerang",
    "Tackle": "Húc",
    "Self-Destruct": "Tự Phát Nổ",
    "Roll Over": "Lăn Tròn",
    "Groundrush": "Lao Đất",
    "Poisonous Breath": "Hơi Thở Độc Tố",
    "Spin Attack": "Xoay Người Tấn Công",
    "Roar": "Gầm Rú",
    "Super Slap": "Siêu Vả",
    "Tremor": "Rung Chấn",
    "Counterslap": "Vả Phản Đòn",
    "Earthquake": "Động Đất",
    "Gnaw": "Gặm Nhấm",
    "Fire": "Hỏa Cầu",
    "Lightning": "Tia Sét",
    "Ice": "Băng Cầu",
    "Triple Slap": "Tam Liên Vả",
    "Snowdust": "Bụi Tuyết",
    "Freezing Gaze": "Ánh Nhìn Băng Giá",
    "Powder Cloud": "Mây Bụi",
    "Burning Bite": "Cắn Cháy Bỏng",
    "Frosty Bite": "Cắn Băng Giá",
    "Burning Breath": "Hơi Thở Rực Cháy",
    "Frosty Breath": "Hơi Thở Băng Giá",
    "Soul Breath": "Hơi Thở Linh Hồn",
    "Snowball Throw": "Ném Cầu Tuyết",
    "Snowball Roll": "Lăn Cầu Tuyết",
    "Snowball Ride": "Cưỡi Cầu Tuyết",
    "Alight": "Hạ Cánh",
    "Handstand Snowball Ride": "Chổng Chuối Cưỡi Tuyết",
    "Beat Ground": "Đập Mặt Đất",
    "Body Roll": "Lăn Toàn Thân",
    "Blizzard Breath": "Hơi Thở Bão Tuyết",
    "Munch Mushroom": "Nhai Nấm",
    "Bad Breath": "Hơi Thở Hôi Thối",
    "Very Bad Breath": "Hơi Thở Cực Hôi",
    "Really Bad Breath": "Hơi Thở Siêu Hôi",
    "Chomp": "Ngoạm",
    "Claw": "Cào",
    "Beeswarm": "Bầy Ong Bay",
    "Honey Syrup": "Siro Mật Ong",
    "Howl": "Tiếng Hú",
    "Horn Attack": "Đâm Sừng",
    "Lightning Horn": "Sừng Sấm Sét",
    "Feather Attack": "Lông Vũ Kích",
    "Regen": "Tự Hồi Phục",
    "Reflect": "Phản Đòn Ma Thuật",
    "Haste": "Tăng Tốc",
    "Regen II": "Tự Hồi Phục II",
    "Reflect II": "Phản Đòn Ma Thuật II",
    "Haste II": "Tăng Tốc II",
    "Tornado Tail": "Đuôi Lốc Xoáy",
    "Crushing Bite": "Cắn Nghiền Nát",
    "Crystal Horn": "Sừng Pha Lê",
    "Ultimate Combo": "Liên Hoàn Kích Tối Thượng",
    "Meteo": "Thiên Thạch",
    "Call": "Kêu Gọi",
    "Chain Reaction": "Phản Ứng Dây Chuyền",
    "Super Shell Shield": "Siêu Mai Rùa Hộ Thuẫn",
    "Death Breath": "Hơi Thở Tử Thần",
}

for item in es_data:
    row_idx = item["row"]
    en_text = item["en"]
    if en_text in es_dict:
        ws_es.cell(row_idx, 3).value = es_dict[en_text]

# =========================================================================
# 2. EnemyCoopSkillDataMessage (38 skills)
# =========================================================================
ws_ec = wb["EnemyCoopSkillDataMessage"]
with open("D:/Viet Hoa Game/temp_scripts/EnemyCoopSkillDataMessage.json", "r", encoding="utf-8") as f:
    ec_data = json.load(f)

ec_dict = {
    "Hellflame Hammer": "Búa Lửa Địa Ngục",
    "Icy Sentence": "Bản Án Băng Giá",
    "Delta Attack": "Đòn Đánh Tam Giác Delta",
    "Rocket Rush": "Tên Lửa Vút Bay",
    "Trigger Explosion": "Kích Nổ Vụ Nổ",
    "Bushy Bond": "Liên Kết Đáng Yêu",
    "Thunderclap": "Tiếng Sét Đánh",
    "Thunderstorm": "Bão Sấm Sét",
    "Feed": "Nuôi Ăn",
    "Pengy Fusion": "Hợp Thể Pengy",
    "Hoppy Fusion": "Hợp Thể Hoppy",
    "Empy Fusion": "Hợp Thể Empy",
    "Heavenly Wrath": "Cơn Thịnh Nộ Thiên Đường",
}

for item in ec_data:
    row_idx = item["row"]
    en_text = item["en"]
    if en_text in ec_dict:
        ws_ec.cell(row_idx, 3).value = ec_dict[en_text]

# =========================================================================
# 3. EnemyBossSkillDataMessage (217 skills)
# =========================================================================
ws_eb = wb["EnemyBossSkillDataMessage"]
with open("D:/Viet Hoa Game/temp_scripts/EnemyBossSkillDataMessage.json", "r", encoding="utf-8") as f:
    eb_data = json.load(f)

eb_dict = {
    "Dive Attack": "Lao Xuống Tấn Công",
    "Wing Slice": "Cánh Cắt",
    "Burning Breath": "Hơi Thở Rực Cháy",
    "Blazing Breath": "Hơi Thở Bốc Hỏa",
    "Inhale": "Hít Vào",
    "Frosty Breath": "Hơi Thở Băng Giá",
    "Blizzard Breath": "Hơi Thở Bão Tuyết",
    "Big Bite": "Cú Đớp Lớn",
    "Bodyslam": "Đè Toàn Thân",
    "Water Spray": "Phun Nước",
    "Tsunami": "Sóng Thần",
    "Bellow": "Rống To",
    "Dive": "Lao Xuống",
    "Tidal Wave": "Thủy Triều Sóng Thần",
    "Snowstorm": "Bão Tuyết",
    "Slash": "Chém",
    "Swipe": "Quét Móng",
    "Fire": "Hỏa Cầu",
    "Fire II": "Hỏa Cầu II",
    "Ice": "Băng Cầu",
    "Ice II": "Băng Cầu II",
    "Toxic Breath": "Hơi Thở Độc Hại",
    "Hide in Shell": "Thu Vào Mai Rùa",
    "Emerge from Shell": "Chui Ra Khỏi Mai Rùa",
    "Sweeping Spin": "Xoay Quét Toàn Diện",
    "Lightning II": "Lôi Điệp II",
    "Demi II": "Trọng Lực II",
    "Deadly Claw": "Móng Vuốt Tử Thần",
    "Deadly Bite": "Cú Cắn Tử Thần",
    "Transform": "Biến Hình",
    "Golden Claw": "Móng Vuốt Hoàng Kim",
    "Golden Fang": "Nanh Vuốt Hoàng Kim",
    "Golden Wind": "Gió Hoàng Kim",
    "Slow": "Làm Chậm",
    "Stop": "Ngưng Đọng",
    "Missile Punch": "Đấm Tên Lửa",
    "Twin Missile Punch": "Song Đấm Tên Lửa",
    "Laser Beam": "Tia Laser",
    "Rampage": "Cuồng Nộ Hung Tợn",
    "Slow II": "Làm Chậm II",
    "Stop II": "Ngưng Đọng II",
    "Blowback": "Thổi Bay",
    "Tackle": "Húc",
    "Horn Slice": "Sừng Chém",
    "Poison Needle": "Kim Độc",
    "Sticky Thread": "Tơ Nhầy Dính",
    "Pengy Rebirth": "Pengy Tái Sinh",
    "Royal Fusion": "Hoàng Gia Hợp Thể",
    "Royal Bite": "Cú Đớp Hoàng Gia",
    "Power Vacuum": "Hút Chân Không Uy Lực",
    "Pengy Missile": "Tên Lửa Pengy",
    "Power Dive": "Lao Xuống Sức Mạnh",
    "Combo Attack 1 (Not used)": "Liên Hoàn Kích 1",
    "Combo Attack 2 (Not used)": "Liên Hoàn Kích 2",
    "Gale Rush": "Lao Như Gió Lốc",
    "Scratch 1 (Not used)": "Cào 1",
    "Scratch 2 (Not used)": "Cào 2",
    "Scratch 3 (Not used)": "Cào 3",
    "Scratch 4 (Not used)": "Cào 4",
    "Bite (Not used)": "Cắn",
    "Scorching Rush": "Lao Rực Lửa",
    "Glacial Rush": "Lao Băng Giá",
    "Thunder Rush": "Lao Sấm Sét",
    "Hell Rush": "Lao Địa Ngục",
    "Horn Toss": "Hất Sừng",
    "Ferocious Charge": "Xung Kích Hung Tợn",
    "Angry Stamp": "Dậm Chân Giận Dữ",
    "Sheep Howl": "Tiếng Cừu Kêu",
    "Huddle": "Tụ Lại",
    "Hibernate": "Ngủ Đông",
    "Spell Stream": "Dòng Chảy Phép Thuật",
    "Flare": "Bộc Phá",
    "Holy Light": "Thánh Lực",
    "Demi": "Trọng Lực",
    "Drain": "Hút Máu",
    "Osmose": "Hút Năng Lượng",
    "Summon": "Triệu Hồi",
    "Dragonic Tail": "Đuôi Long Thần",
    "Dragonic Breath": "Hơi Thở Long Thần",
    "Dragonic Rage": "Cơn Thịnh Nộ Long Thần",
    "Dragnarok": "Tận Thế Rồng",
    "Swallow": "Nuốt Chửng",
    "Stab": "Đâm",
    "Sweeping Slash": "Chém Quét",
    "Spinning Slash": "Chém Xoay Tròn",
    "Haste": "Tăng Tốc",
    "Comet": "Sao Băng",
    "Meteo": "Thiên Thạch",
    "Shooting Star": "Băng Sao Rơi",
    "Self-Renewal 1": "Tự Tái Sinh 1",
    "Self-Renewal 2": "Tự Tái Sinh 2",
    "Self-Renewal 3": "Tự Tái Sinh 3",
    "Self-Renewal 4": "Tự Tái Sinh 4",
    "Self-Renewal 5": "Tự Tái Sinh 5",
    "Burning Aura": "Hào Quang Rực Cháy",
    "Frosty Aura": "Hào Quang Băng Giá",
    "Electric Aura": "Hào Quang Điện Giật",
    "Dark Aura": "Hào Quang Hắc Ám",
    "Time Jump": "Bước Nhảy Thời Gian",
    "Time Slip": "Trượt Thời Gian",
    "Mighty Fist": "Nắm Đấm Uy Dũng",
    "Great Hammer": "Đại Chiến Búa",
    "Cyclone Tail": "Đuôi Cuồng Phong",
    "Bend Space": "Bẻ Cong Không Gian",
    "Condense Time": "Ngưng Tụ Thời Gian",
    "Space-Time Collapse": "Sụp Đổ Không-Thời Gian",
    "Inner Darkness": "Bóng Tối Nội Tâm",
    "Wind Back Time": "Quay Ngược Thời Gian",
    "Speed Up Time": "Đẩy Nhanh Thời Gian",
    "Space-Time Wall": "Tường Không-Thời Gian",
    "Space-Time Mirror": "Gương Không-Thời Gian",
    "Long-Range Punch": "Cú Đấm Tầm Xa",
    "Machine Gun Punch": "Cú Đấm Súng Máy",
    "Scatter Laser": "Laser Phân Tán",
    "Pinpoint Laser": "Laser Chuẩn Điểm",
    "Monster Blade": "Yêu Đao",
    "Monster Blade: Circle Slash": "Yêu Đao: Trảm Tròn",
    "Monster Blade: Earthdrive": "Yêu Đao: Xé Đất",
    "Monster Blade: Back Slash": "Yêu Đao: Trảm Lưng",
    "Monster Blade: Finishing Blow": "Yêu Đao: Đòn Kết Liễu",
    "Howl": "Tiếng Gầm",
    "Death Throes": "Cơn Giãy Giụa Hấp Hối",
    "Two-Sword Style": "Song Kiếm Phái",
    "Blunt Blow": "Sống Đao Trảm",
    "Wind Slash": "Phong Trảm",
    "Double Back": "Hoàn Trả",
    "Stone Slash": "Thạch Trảm",
    "Rebellion": "Phản Kháng",
    "Monster Sword": "Yêu Kiếm",
    "Cure II": "Trị Liệu II",
    "Life II": "Hồi Sinh II",
    "Monster Axe": "Yêu Rìu",
    "Monster Hammer": "Yêu Búa",
    "Scythe Attack": "Lưỡi Hái Kích",
    "Helix Slash": "Xoáy Tử Thần",
    "Dark Mist": "Hắc Vụ",
    "Cursed Slash": "Nguyền Trảm",
    "Endark": "Ban Hắc",
    "Earthsplitter": "Phá Địa Trảm",
    "Hellfire": "Ngục Hỏa",
    "Absorb": "Hấp Thu",
    "Pandemic": "Đại Dịch",
    "Stalker": "Ảnh Tung",
    "Snatch": "Đoạt Hồn",
    "Moonlight Butterfly": "Hồ Điệp Nguyệt Quang",
    "Black Hole": "Hố Đen",
    "Dark Pact": "Hắc Khế",
    "Dark Matter": "Hắc Thể",
    "Hoppy Rebirth": "Hoppy Tái Sinh",
    "Suck In": "Hút Vào",
    "Penguin Missile": "Tên Lửa Chim Cánh Cụt",
    "Empy Rebirth": "Empy Tái Sinh",
    "Sacrifice...": "Vật hiến tế...",
    "I have found you...": "Ta đã tìm thấy ngươi...",
    "You shall die here, sacrifice...": "Ngươi sẽ phải chết tại đây, vật hiến tế...",
    "*Its beak is seething with heat...*": "*Cái mỏ của nó đang sôi sục nhiệt lượng...*",
    "*Accumulating power...*": "*Đang tụ lực...*",
}

for item in eb_data:
    row_idx = item["row"]
    en_text = item["en"]
    if en_text in eb_dict:
        ws_eb.cell(row_idx, 3).value = eb_dict[en_text]

wb.save(excel_path)
print("Updated EnemySkillDataMessage, EnemyCoopSkillDataMessage, EnemyBossSkillDataMessage successfully (344 entries)!")
