import openpyxl

excel_path = "D:/Viet Hoa Game/I_am_Setsuna-parameter-Steam.xlsx"
wb = openpyxl.load_workbook(excel_path)

# =========================================================================
# 1. PlayerSetParameterMessage
# =========================================================================
ws_player = wb["PlayerSetParameterMessage"]
player_names = {
    6: "Endir",
    8: "Setsuna",
    10: "Aeterna",
    12: "Nidr",
    14: "Kir",
    16: "Julienne",
    18: "Fides",
}
for r, name in player_names.items():
    ws_player.cell(r, 3).value = name

# =========================================================================
# 2. EnemySetParameterMessage
# =========================================================================
ws_enemy = wb["EnemySetParameterMessage"]
enemy_trans = {
    6: "Pengy",
    8: "Hoppy",
    10: "Empy",
    12: "Rocky",
    14: "Scarly",
    16: "Hoot-Hoot",
    18: "Toot-Hoot",
    20: "Woot-Hoot",
    22: "Zoot-Hoot",
    24: "Flapper Trắng",
    26: "Flapper Đen",
    28: "Flapper Cầu Vồng",
    30: "Flapper Đá",
    32: "Skullian",
    34: "Spikoon",
    36: "Armonite",
    38: "Ốc Phóng Xạ",
    40: "Puff-Puff Độc",
    42: "Puff-Puff Gai",
    44: "Puff-Puff Lửa",
    46: "Puff-Puff Nguyên Tử",
    48: "Waloompa",
    50: "Baloompa",
    52: "Galoompa",
    54: "Maloompa",
    56: "Muffy",
    58: "Chocolly",
    60: "Sherbetty",
    62: "Jewelly",
    64: "Versa",
    66: "Vulpara",
    68: "Lupara",
    70: "Silvara",
    72: "Snecter",
    74: "Trăn Hổ",
    76: "Rắn Địa Ngục",
    78: "Trăn Ma Thuật",
    80: "Roly-Poly",
    82: "Bowly-Poly",
    84: "Snowly-Poly",
    86: "Glowly-Poly",
    88: "Nấm Lưng Gai",
    90: "Nấm Lưng Núi",
    92: "Nấm Lưng Hang",
    94: "Nấm Lưng Pha Lê",
    96: "Jaboo",
    98: "Uppa",
    100: "Hookee",
    102: "Southpaw",
    104: "Deermon Nhỏ",
    106: "Deermon Lớn",
    108: "Đại Deermon",
    110: "Deermon Số",
    112: "Deermon Triệu Hồi",
    114: "Heroniel",
    116: "Peacockiel",
    118: "Condoriel",
    120: "Stoniel",
    122: "Summoniel",
    124: "Dinotaurus",
    126: "Dinotaurus Khổng Lồ",
    128: "Dinotaurus Đại Đế",
    130: "Dinotaurus Pha Lê",
    132: "Bạch Phong",
    134: "Dị Thú Có Cánh",
    136: "Schwarzstrom",
    138: "Schwarzstrom",
    140: "Dị Thú Vảy Rồng",
    142: "Thanh Niên Mũm Mĩm",
    144: "Thanh Niên Mắt Sắc",
    146: "Thanh Niên Mặt Trẻ Con",
    148: "Binh Lính",
    150: "Rùa Nguyên Thủy",
    152: "Dị Thú Mai Rùa",
    154: "Bá Tước Sói",
    156: "Thiết Bị Spritnite",
    158: "Nô Lệ Thời Gian",
    160: "Grinche",
    162: "Bọ Cánh Cứng Giáp Sắt",
    164: "Pengy Vua",
    166: "Hoppy Vua",
    168: "Empy Vua",
    170: "Hổ Bình Minh",
    172: "Dị Thú Nanh Nhọn",
    174: "Cừu Béo",
    176: "Rhydderch",
    178: "Quái Vật Dị Dạng",
    180: "Quái Vật Dị Dạng",
    182: "Luân Hồi Hắc Ám",
    184: "Thiếu Niên",
    186: "Chúa Tể Thời Gian",
    188: "Syg",
    190: "Quotra",
    192: "Tronne",
    194: "Thần Chết",
    196: "Thần Chết",
    198: "Thần Chết",
    200: "Thần Chết",
    202: "Thẩm Phán Thời Gian",
    204: "Hapsper",
    206: "Freyja",
    208: "Sayagi",
}
for r, name in enemy_trans.items():
    ws_enemy.cell(r, 3).value = name

# =========================================================================
# 3. NPCSetParameterMessage
# =========================================================================
ws_npc = wb["NPCSetParameterMessage"]
npc_dict = {
    "???": "???",
    "Abe": "Abe",
    "Agitated Aide": "Phụ Tá Bồn Chồn",
    "Ambitious Girl": "Cô Gái Đầy Hoài Bão",
    "Angel-Voiced Little Girl": "Bé Gái Giọng Thiên Thần",
    "Anxious Man": "Người Đàn Ông Lo Lắng",
    "Apothecary": "Dược Sĩ",
    "Aspiring Researcher": "Nhà Nghiên Cứu Tập Sự",
    "Aurorean Tiger's Memories": "Ký Ức Của Hổ Bình Minh",
    "Awestruck Young Man": "Thanh Niên Kinh Ngạc",
    "Awkwardly Dressed Young Man": "Thanh Niên Ăn Mặc Kỳ Quặc",
    "Azuma": "Azuma",
    "Baby-Faced Young Man": "Thanh Niên Mặt Trẻ Con",
    "Banno": "Banno",
    "Beady-Eyed Soldier": "Binh Lính Mắt Hạt Tiêu",
    "Bird C1": "Chim C1",
    "Bird C2": "Chim C2",
    "Bird C3": "Chim C3",
    "Blacksmith": "Thợ Rèn",
    "Bomb A1": "Bom A1",
    "Bomb A2": "Bom A2",
    "Bomb A3": "Bom A3",
    "Bored-Looking Old Man": "Ông Lão Trông Buồn Chán",
    "Calm Old Lady": "Bà Cụ Điềm Đạm",
    "Carboceros Beetle's Memories": "Ký Ức Bọ Giáp Sắt",
    "Carefree Girl": "Cô Gái Vô Tư",
    "Cave Coccoon 1": "Kén Hang Động 1",
    "Cave Coccoon 2": "Kén Hang Động 2",
    "Cave Coccoon 3": "Kén Hang Động 3",
    "Cheerful Girl": "Cô Gái Vui Vẻ",
    "Chef": "Đầu Bếp",
    "Children": "Lũ Trẻ",
    "Citadel Guard A": "Lính Gác Thành A",
    "Citadel Guard B": "Lính Gác Thành B",
    "Citadel Guard C": "Lính Gác Thành C",
    "Citadel Guard D": "Lính Gác Thành D",
    "Citadel Guard E": "Lính Gác Thành E",
    "Citadel Guard F": "Lính Gác Thành F",
    "Citadel Knight A": "Hiệp Sĩ Thành A",
    "Confused Young Man": "Thanh Niên Bối Rối",
    "Contemplative Boy": "Cậu Bé Trầm Tư",
    "Contemplative Young Man": "Thanh Niên Trầm Tư",
    "Crooked-Toothed Man": "Người Đàn Ông Răng Khểnh",
    "Debugger A": "Gỡ Lỗi A",
    "Debugger B": "Gỡ Lỗi B",
    "Deep-Voiced Little Boy": "Cậu Bé Giọng Trầm",
    "Deep-Voiced Lumberjack": "Tiều Phu Giọng Trầm",
    "Dewy-Eyed Little Girl": "Bé Gái Mắt Long Lanh",
    "Dimple-Cheeked Little Girl": "Bé Gái Má Lúm Đồng Tiền",
    "Double-Chinned Man": "Người Đàn Ông Hai Cằm",
    "Double-Chinned Young Man": "Thanh Niên Hai Cằm",
    "Doumae": "Doumae",
    "Downcast-Looking Knight": "Hiệp Sĩ Trông U Sầu",
    "Dutiful Soldier": "Binh Lính Tận Tụy",
    "Dying Man": "Người Đàn Ông Hấp Hối",
    "Dysphormic Monster's Memories": "Ký Ức Quái Vật Dị Dạng",
    "Easygoing Mayor": "Thị Trưởng Dễ Tính",
    "Eater Enemy A1": "Kẻ Nuốt Chửng A1",
    "Eater Enemy A2": "Kẻ Nuốt Chửng A2",
    "Elderly Farmer": "Lão Nông",
    "Elderly Traveler": "Lữ Khách Cao Tuổi",
    "Enthusiastic Girl": "Cô Gái Nhiệt Tình",
    "Entrance to the Royal Valley": "Lối Vào Thung Lũng Hoàng Gia",
    "Ever-Hungry Man": "Gã Lúc Nào Cũng Đói",
    "Finely Chiseled Knight": "Hiệp Sĩ Khôi Ngô",
    "Flat-Nosed Little Boy": "Cậu Bé Mũi Tẹt",
    "Forlorn Girl": "Cô Gái Cô Đơn",
    "Frail-Looking Man": "Người Đàn Ông Yếu Ớt",
    "Frail-Looking Young Man": "Thanh Niên Yếu Ớt",
    "Freckly Old Woman": "Bà Cụ Tàn Nhang",
    "Freyja's Memories": "Ký Ức Của Freyja",
    "Friendly Boy": "Cậu Bé Thân Thiện",
    "Frown-Marked Old Woman": "Bà Cụ Nhăn Nhó",
    "Generic Examine Point": "Điểm Kiểm Tra",
    "Gentle Old Woman": "Bà Lão Dịu Dàng",
    "Gentle-Mannered Man": "Người Đàn Ông Lịch Thiệp",
    "Gentle-Voiced Man": "Người Đàn Ông Giọng Nhẹ Nhàng",
    "Giddy Knight": "Hiệp Sĩ Lăng Xăng",
    "Good-Natured Lady": "Phu Nhân Nhân Hậu",
    "Gossipy Girl": "Cô Gái Thích Hóng Chuyện",
    "Grass-Stained Little Boy": "Cậu Bé Lấm Lem Cỏ",
    "Grinche's Memories": "Ký Ức Của Grinche",
    "Grubbily Clothed Aide": "Phụ Tá Áo Quần Lôi Thôi",
    "Hapsper's Memories": "Ký Ức Của Hapsper",
    "Hashimoto": "Hashimoto",
    "Hasty Soldier": "Binh Lính Vội Vã",
    "Hayashi": "Hayashi",
    "Healthy Little Boy": "Cậu Bé Khỏe Khoắn",
    "Hermit Crab C1": "Ốc Mượn Hồn C1",
    "Hermit Crab C2": "Ốc Mượn Hồn C2",
    "Hermit Crab C3": "Ốc Mượn Hồn C3",
    "Higami": "Higami",
    "Hoarse-Voiced Merchant": "Thương Nhân Khàn Giọng",
    "Honest Knight": "Hiệp Sĩ Trung Thực",
    "Hoshiyama": "Hoshiyama",
    "Humble Maid": "Hầu Gái Khiêm Nhường",
    "Humming Man": "Người Đàn Ông Ngân Nga",
    "Husky-Voiced Woman": "Người Phụ Nữ Giọng Khàn",
    "Idle Old Woman": "Bà Lão Nhàn Rỗi",
    "Imposing Village Chief": "Trưởng Làng Uy Nghi",
    "Innocent-Looking Little Boy": "Cậu Bé Trông Ngây Thơ",
    "Insufferable Man": "Gã Khó Ưa",
    "Inubushi": "Inubushi",
    "Irritable Man": "Người Đàn Ông Dễ Nổi Cáu",
    "Irritated-Looking Waitress": "Cô Phục Vụ Trông Bực Bội",
    "Jaboo's Memories": "Ký Ức Của Jaboo",
    "Kakefuda": "Kakefuda",
    "Kamimura": "Kamimura",
    "Kawawa": "Kawawa",
    "Kind Woman": "Người Phụ Nữ Hiền Hậu",
    "Kind Young Woman": "Cô Gái Hiền Hậu",
    "Kind-Looking Lady": "Quý Bà Nhân Từ",
    "King Hoppy's Memories": "Ký Ức Của Hoppy Vua",
    "Kita": "Kita",
    "Kitao": "Kitao",
    "Knights": "Các Hiệp Sĩ",
    "Konishi": "Konishi",
    "Kuranari": "Kuranari",
    "Kurino": "Kurino",
    "Kurose": "Kurose",
    "Lookout": "Lính Canh Gác",
    "Loud Soldier": "Binh Lính Oang Oang",
    "Magic Consortium Member": "Thành Viên Thương Hội Ma Đạo",
    "Makeup-Caked Woman": "Người Phụ Nữ Đậm Phấn Son",
    "Matsuda": "Matsuda",
    "Mature Little Girl": "Bé Gái Chín Chắn",
    "Merry Little Girl": "Bé Gái Rạng Rỡ",
    "Moriga": "Moriga",
    "Murakami": "Murakami",
    "Nagase": "Nagase",
    "Nervous Traveler": "Khách Đi Đường Bồn Chồn",
    "Neurotic Man": "Người Đàn Ông Hay Lo",
    "Nishioka": "Nishioka",
    "Nive Village Chief": "Trưởng Làng Nive",
    "Okamura": "Okamura",
    "Old Woman's Chakram Shard": "Mảnh Luân Đao Của Bà Lão",
    "Outdoor Man": "Người Đàn Ông Phong Trần",
    "Over-the-Top Young Man": "Thanh Niên Làm Quá",
    "Overly Familiar Young Man": "Thanh Niên Quá Suồng Sã",
    "Pale-Faced Young Man": "Thanh Niên Mặt Tái Nhợt",
    "Passionate Boy": "Cậu Bé Nhiệt Huyết",
    "Passionate Young Man": "Thanh Niên Nhiệt Huyết",
    "Penguin A1": "Chim Cánh Cụt A1",
    "Penguin A2": "Chim Cánh Cụt A2",
    "Penguin A3": "Chim Cánh Cụt A3",
    "Penguin B1": "Chim Cánh Cụt B1",
    "Penguin B2": "Chim Cánh Cụt B2",
    "Penguin C1": "Chim Cánh Cụt C1",
    "Penguin C2": "Chim Cánh Cụt C2",
    "Penguin C3": "Chim Cánh Cụt C3",
    "Perfect-Nosed Girl": "Cô Gái Mũi Đẹp",
    "Perfectly Toothed Girl": "Cô Gái Răng Đều",
    "Plain-Looking Old Woman": "Bà Lão Giản Dị",
    "Plump Young Man": "Thanh Niên Mũm Mĩm",
    "Primeval Tortoise's Memories": "Ký Ức Rùa Nguyên Thủy",
    "Quiet Man": "Người Đàn Ông Trầm Lặng",
    "Quiet Mother": "Người Mẹ Trầm Lặng",
    "Red-Cheeked Little Boy": "Cậu Bé Má Đỏ",
    "Red-Faced Old Man": "Ông Lão Mặt Đỏ",
    "Rhydderch's Memories": "Ký Ức Của Rhydderch",
    "Round-Cheeked Little Boy": "Cậu Bé Má Tròn Phúng Phính",
    "Round-Eyed Man": "Người Đàn Ông Mắt Tròn",
    "Round-Eyed Young Man": "Thanh Niên Mắt Tròn",
    "Round-Faced Man": "Người Đàn Ông Mặt Tròn",
    "Round-Faced Young Man": "Thanh Niên Mặt Tròn",
    "Rude Soldier": "Binh Lính Thô Lỗ",
    "Ruler of Time's Memories": "Ký Ức Chúa Tể Thời Gian",
    "Sad Boy": "Cậu Bé Đượm Buồn",
    "Sakai": "Sakai",
    "Sasaki": "Sasaki",
    "Scar-Faced Man": "Người Đàn Ông Mặt Sẹo",
    "Scatterbrained Old Woman": "Bà Cụ Hay Quên",
    "Scrawny Boy": "Cậu Bé Gầy Gò",
    "Sea Dragon": "Hải Long",
    "Sea Lion A1": "Hải Cẩu A1",
    "Sealed Entrance to Blizzard Cave": "Lối Vào Hang Bão Tuyết Đã Niêm Phong",
    "Seedy-Looking Man": "Gã Trông Nhếch Nhác",
    "Self-Disciplined Young Man": "Thanh Niên Kỷ Luật",
    "Sharp-Eyed Young Man": "Thanh Niên Mắt Tinh Anh",
    "Shimoyama": "Shimoyama",
    "Shrewd-Eyed Young Man": "Thanh Niên Mắt Sắc Sảo",
    "Silky-Skinned Old Man": "Ông Lão Da Mịn",
    "Sincere Soldier": "Binh Lính Chân Thành",
    "Sleepy-Eyed Soldier": "Binh Lính Ngái Ngủ",
    "Smiling Aide": "Phụ Tá Hay Cười",
    "Smug-Looking Man": "Người Đàn Ông Đắc Ý",
    "Snotty-Nosed Little Boy": "Cậu Bé Thò Lò Mũi",
    "Snow-Roller A1": "Lăn Tuyết A1",
    "Snow-Roller A2": "Lăn Tuyết A2",
    "Snow-Woman A1": "Tuyết Nữ A1",
    "Snow-Woman A2": "Tuyết Nữ A2",
    "Snub-Nosed Knight": "Hiệp Sĩ Mũi Hếch",
    "Sociable Young Man": "Thanh Niên Hòa Đồng",
    "Soil-Stained Woman": "Người Phụ Nữ Lấm Bụi Đất",
    "Soldier": "Binh Lính",
    "Solemn-Faced Young Man": "Thanh Niên Nghiêm Nghị",
    "Sour-Faced Knight": "Hiệp Sĩ Mặt Cau Có",
    "Spritnite Device (After Destruction)": "Thiết Bị Spritnite (Đã Phá Hủy)",
    "Spritnite Device (Before Destruction)": "Thiết Bị Spritnite (Chưa Phá Hủy)",
    "Spritnite Vein (Right)": "Mạch Quặng Spritnite (Đúng)",
    "Spritnite Vein (Wrong)": "Mạch Quặng Spritnite (Sai)",
    "Stern-Faced Old Woman": "Bà Lão Nghiêm Nghị",
    "Stern-Faced Woman": "Người Phụ Nữ Nghiêm Nghị",
    "Stout Sheep's Memories": "Ký Ức Của Cừu Béo",
    "Strong Old Man": "Ông Lão Vạm Vỡ",
    "Strong-Looking Woman": "Người Phụ Nữ Trông Khỏe Khoắn",
    "Suspicious Man": "Người Đàn Ông Đáng Ngờ",
    "Suzuki": "Suzuki",
    "Takahashi": "Takahashi",
    "Takei": "Takei",
    "Takenaka": "Takenaka",
    "The Three Sisters' Memories": "Ký Ức Của Ba Chị Em",
    "Thin-Faced Soldier": "Binh Lính Mặt Gầy",
    "Thin-Lipped Woman": "Người Phụ Nữ Môi Mỏng",
    "Time Judge's Memories": "Ký Ức Thẩm Phán Thời Gian",
    "Timeslave's Memories": "Ký Ức Nô Lệ Thời Gian",
    "Toothless Old Man": "Ông Lão Móm Mém",
    "Tsuritani": "Tsuritani",
    "Uchibori": "Uchibori",
    "Uezono": "Uezono",
    "Uncomfortable-Looking Man": "Người Đàn Ông Khó Chịu",
    "Unhealthy-Looking Young Man": "Thanh Niên Trông Xanh Xao",
    "Unremarkable Young Man": "Thanh Niên Tầm Thường",
    "Village Administrator": "Quan Quản Lý Làng",
    "Villager": "Dân Làng",
    "Warmly Dressed Little Boy": "Cậu Bé Mặc Áo Ấm",
    "Weary Young Man": "Thanh Niên Mệt Mỏi",
    "Well-Built Man": "Người Đàn Ông Cường Tráng",
    "White-Bearded Man": "Người Đàn Ông Râu Trắng",
    "White-Toothed Little Girl": "Bé Gái Răng Trắng Tinh",
    "Whitewind's Memories": "Ký Ức Của Bạch Phong",
    "Wide-Eyed Boy": "Cậu Bé Mắt Tròn Xoe",
    "Wolf Baron's Memories": "Ký Ức Của Bá Tước Sói",
    "Wrinkled Old Man": "Ông Lão Già Nua",
    "Wrinkled Worker": "Người Thợ Già Nua",
    "Yakabe": "Yakabe",
    "Yamamoto": "Yamamoto",
    "Yano": "Yano",
    "Yoshikawa": "Yoshikawa",
    "Youthful Girl": "Cô Gái Trẻ Trung",
    "Youthful Woman": "Người Phụ Nữ Trẻ Trung",
    "Yura": "Yura",
}

updated_npc = 0
for r in range(2, ws_npc.max_row + 1):
    en = ws_npc.cell(r, 2).value
    vn = ws_npc.cell(r, 3).value
    if en is not None:
        en_str = str(en).strip()
        if en_str in npc_dict and (vn is None or not str(vn).strip()):
            ws_npc.cell(r, 3).value = npc_dict[en_str]
            updated_npc += 1

wb.save(excel_path)
print(f"Updated PlayerSetParameterMessage: {len(player_names)} entries.")
print(f"Updated EnemySetParameterMessage: {len(enemy_trans)} entries.")
print(f"Updated NPCSetParameterMessage: {updated_npc} entries.")
