import openpyxl
import json

excel_path = "D:/Viet Hoa Game/I_am_Setsuna-parameter-Steam.xlsx"
wb = openpyxl.load_workbook(excel_path)

# =========================================================================
# TwoPlayerCoopSkillDataMessage (63 skills)
# =========================================================================
ws2 = wb["TwoPlayerCoopSkillDataMessage"]
two_coop = {
    6: "Hồi Phục Toàn Diện",
    7: "Hồi phục HP cho toàn bộ đồng minh, và giải trừ toàn bộ\ntrạng thái bất lợi. (Hào Quang/Cầu Nguyện)",
    8: "Lôi Điệp Trảm",
    9: "Gây sát thương đặc biệt [Quang] lên kẻ địch gần mục tiêu.\nGây thêm sát thương khi đánh trúng điểm yếu. (Trảm Kích/Lôi Điệp II)",
    10: "Đồng Bộ Hóa",
    11: "Niệm Đồng Bộ lên toàn đội. Mỗi chỉ số của mọi người\nsẽ bằng với chỉ số cao nhất của người trong đội. (Chiến Hống/Cổ Vũ)",
    12: "Song Trảm X",
    13: "Gây sát thương vật lý [Vô hệ] lên kẻ địch gần mục tiêu.\nCàng tung đòn giao kiếm sớm sát thương càng cao. (Cuồng Phong/Xung Kích)",
    14: "Quá Tải",
    15: "Niệm Hành Động Kép lên một đồng minh, giúp kích hoạt\nhiệu ứng 2 lần khi dùng chế độ Xung Lực. (Tăng Tốc/Hoàn Bích Kích)",
    16: "Chuyển Pha",
    17: "Gây sát thương đặc biệt [Vô hệ] lên kẻ địch gần mục tiêu.\nĐồng thời gia tăng thanh SP của toàn đội. (Giác Ngộ/Vạn Vật)",
    18: "Thập Tự Trảm",
    19: "Kiếm khí để lại hình chữ thập gây sát thương vật lý\n[Vô hệ] lên toàn bộ kẻ địch. (Kiếm Khí/Phong Trảm)",
    20: "Chấn Động Cuồng Nộ",
    21: "Gây sát thương vật lý [Vô hệ] lên toàn bộ kẻ địch.\nCó thể gây Tê Liệt, Hỗn Loạn và Choáng. (Chấn Động/Khiêu Khích)",
    22: "Ẩn Thân Trảm",
    23: "Gây sát thương vật lý [Vô hệ] lên kẻ địch gần mục tiêu,\nbỏ qua 30% Phòng Thủ, tỉ lệ chí mạng rất cao. (Tia Lửa/Khuếch Tán)",
    24: "Hấp Huyết Trảm",
    25: "Gây sát thương đặc biệt [Vô hệ] lên kẻ địch gần mục tiêu.\nToàn đội hút 40% sát thương gây ra thành HP. (Quang Mang/Hút Máu)",
    26: "Hỏa Trảm Kích",
    27: "Gây sát thương đặc biệt [Hỏa] lên kẻ địch gần mục tiêu.\nGây thêm sát thương khi đánh trúng điểm yếu. (Trảm Kích/Hỏa Cầu II)",
    28: "Song Thiên Thạch",
    29: "Vô số thiên thạch trút xuống, gây sát thương ma thuật\n[Vô hệ] bỏ qua 50% Phòng Thủ lên toàn bộ kẻ địch. (Thiên Thạch/Kích Hoạt Ma Lực)",
    30: "Băng Tường",
    31: "Dựng bức tường băng bảo vệ toàn đội, tăng kháng ma thuật\nvà gây sát thương ma thuật [Thủy] khi bị đánh. (Bức Tường/Băng Kích II)",
    32: "Băng Trảm Kích",
    33: "Gây sát thương đặc biệt [Thủy] lên kẻ địch gần mục tiêu.\nGây thêm sát thương khi đánh trúng điểm yếu. (Trảm Kích/Băng Kích II)",
    34: "Đại Thiên Thạch",
    35: "Thiên thạch hủy diệt giáng xuống, gây sát thương ma thuật\n[Vô hệ] cực lớn lên toàn bộ kẻ địch. (Thiên Thạch/Băng Kích II)",
    36: "Sóng Bóng Tối",
    37: "Phóng sóng hắc ám gây sát thương ma thuật [Hắc Ám]\nlên toàn bộ kẻ địch trên một đường thẳng. (Kiếm Khí/Hắc Vụ)",
    38: "Bình Minh U Tối",
    39: "Gây sát thương đặc biệt [Quang+Hắc Ám] lên toàn bộ kẻ địch.\nKèm theo hàng loạt trạng thái bất lợi. (Tập Kích/Ngục Hỏa)",
    40: "Thần Cơ",
    41: "Cường hóa toàn bộ chỉ số cho toàn đội, đồng thời nạp đầy\nthanh ATB ngay lập tức. (Khởi Nguyên/Tận Thế Rồng)",
    42: "Hòa Âm Tuyệt Đối",
    43: "Hồi phục toàn bộ HP và MP cho toàn đội, đồng thời tăng\ntốc độ nạp thanh ATB. (Cầu Nguyện/Luân Xa)",
    44: "Rực Rỡ",
    45: "Gây sát thương ma thuật [Quang] lên toàn bộ kẻ địch,\nđồng thời làm mù mắt và giảm chỉ số của chúng. (Thánh Lực/Bảo Vệ)",
    46: "Dây Cứu Sinh",
    47: "Ban hiệu ứng Tự Động Hồi Sinh và hồi phục HP liên tục\ncho toàn bộ đồng minh. (Hồi Sinh II/Hồi Phục)",
    48: "Cột Thu Lôi",
    49: "Triệu hồi sấm sét giáng xuống kẻ địch bị khiêu khích,\ngây sát thương ma thuật [Quang] diện rộng. (Khiêu Khích/Lôi Điệp II)",
    50: "Ý Chí Bất Diệt",
    51: "Gia tăng Phòng Thủ cực đại và ngăn toàn đội bị hạ gục\ntrong lượt tiếp theo. (Khích Lệ/Kiên Cường)",
    52: "Bão Từ Trường",
    53: "Tạo cơn bão sấm sét và từ trường, gây sát thương ma thuật\n[Quang] và gây Tê Liệt toàn bộ kẻ địch. (Lôi Điệp II/Chấn Động)",
    54: "Sóng Băng Giá",
    55: "Phóng sóng băng tuyết gây sát thương ma thuật [Thủy]\nvà đóng băng toàn bộ kẻ địch. (Thánh Quang/Băng Thương)",
    56: "Hỏa Sơn Trảm",
    57: "Kết hợp lửa và đất đá tạo vụ nổ dung nham, gây sát thương\nma thuật [Hỏa] lên kẻ địch gần mục tiêu. (Hỏa Cầu II/Nham Thạch)",
    58: "Siêu Tân Tinh",
    59: "Giải phóng vụ nổ ánh sáng cực đại, gây sát thương đặc biệt\n[Quang] cực lớn lên toàn bộ kẻ địch. (Tỏa Sáng/Hư Vô)",
    60: "Điện Từ",
    61: "Tạo trường điện từ gây sát thương ma thuật [Quang]\nvà làm giảm mạnh tốc độ của toàn bộ kẻ địch. (Lôi Điệp/Làm Chậm)",
    62: "Đại Trị Liệu",
    63: "Hồi phục đầy 100% HP và MP cho toàn đội, giải trừ mọi\ntrạng thái bất lợi. (Trị Liệu II/Hồi Phục)",
    64: "Can Thiệp",
    65: "Chặn đứng hành động của kẻ địch và phản hồi lại bằng đòn\ntấn công vật lý [Vô hệ]. (Tiếp Ứng/Phản Đòn)",
    66: "Thập Tự Va Chạm",
    67: "Hai luồng kiếm khí va chạm tạo xung lực chấn động, gây sát thương\nvật lý [Vô hệ] lên toàn bộ kẻ địch. (Kiếm Khí/Xuyên Tâm)",
    68: "Lực Hút Chân Không",
    69: "Tạo luồng gió hút kẻ địch lại và tăng tốc độ ATB\ncho toàn bộ đồng minh. (Phong Trảm/Tăng Tốc)",
    70: "Hắc Thánh Quang",
    71: "Kết hợp sức mạnh Ánh Sáng và Bóng Tối, gây sát thương đặc biệt\n[Quang+Hắc Ám] lên toàn bộ kẻ địch. (Thánh Quang/Hắc Vụ)",
    72: "Chiến Lũy",
    73: "Dựng chiến lũy phòng thủ kiên cố, giảm 80% mọi sát thương\ncho toàn đội trong 2 lượt. (Bảo Vệ/Phòng Thủ Bất Bại)",
    74: "Huyễn Ảnh Phá",
    75: "Phân thân ảo ảnh tấn công dồn dập, gây sát thương vật lý\n[Vô hệ/8 đòn] lên kẻ địch gần mục tiêu. (Ảo Ảnh/Toái Thương Kích)",
    76: "Liều Mạng",
    77: "Đổi toàn bộ phòng thủ lấy sức tấn công bùng nổ, gây sát thương\nvật lý [Vô hệ] cực lớn. (Cuồng Nộ/Phản Kháng)",
    78: "Xoáy Lửa",
    79: "Tạo lốc xoáy rực lửa thiêu rụi toàn bộ kẻ địch,\ngây sát thương ma thuật [Hỏa] diện rộng. (Hỏa Cầu/Cuồng Phong Đao)",
    80: "Ảo Ảnh Kích",
    81: "Tấn công chớp nhoáng từ bóng tối, gây sát thương vật lý\n[Hắc Ám] và giảm chỉ số của địch. (Ảnh Tung/Tập Kích)",
    82: "Thiên Thạch Cóc",
    83: "Triệu hồi thiên thạch kỳ dị hình ếch, gây sát thương đặc biệt\n[Vô hệ] tỉ lệ nghịch với lượng HP hiện tại. (Oa Phách/Thiên Thạch)",
    84: "Hồn Cuồng Nộ",
    85: "Kích hoạt linh hồn chiến binh, tăng mạnh Tấn Công và Chí Mạng\ncho toàn bộ đồng minh. (Chiến Hống/Cuồng Nộ)",
    86: "Thiết Trinh Nữ",
    87: "Nhốt kẻ địch vào trinh nữ sắt, gây sát thương vật lý\n[Hắc Ám] và có tỉ lệ hạ gục tức thì. (Ngục Hỏa/Trọng Lực)",
    88: "Tinh Vân Nở Hoa",
    89: "Khai mở tinh vân ma thuật, gây sát thương đặc biệt [Vô hệ]\nvà nạp đầy thanh SP cho toàn đội. (Vạn Vật/Giác Ngộ)",
    90: "Nghịch Lý",
    91: "Đảo ngược dòng chảy thời gian, hồi sinh toàn đội và đảo ngược\nhiệu ứng bất lợi thành có lợi. (Vĩnh Cửu/Hồi Sinh II)",
    92: "Huyễn Tưởng Khúc",
    93: "Tấu lên khúc nhạc ảo mộng, ru ngủ và gây sát thương ma thuật\n[Thời Gian] lên toàn bộ kẻ địch. (Ngưng Đọng/Thánh Quang)",
    94: "Tinh Thần Kích",
    95: "Phóng chùm sao băng gây sát thương vật lý [Quang/6 đòn]\nlên toàn bộ kẻ địch trên đường thẳng. (Thánh Quang/Hoàn Bích Kích)",
    96: "Độc Dược Trảm",
    97: "Chém lưỡi kiếm tẩm kịch độc, gây sát thương vật lý [Vô hệ]\nvà gây Độc Tố nặng lên kẻ địch. (Độc Tố/Sống Đao Trảm)",
    98: "Ma Đạo Hộ Thuẫn",
    99: "Tạo lá chắn ma thuật phản hồi 50% sát thương phép\nlại cho kẻ tấn công. (Hộ Giáp/Hoàn Trả)",
    100: "Đại Hỏa Bộc",
    101: "Tạo vụ nổ lửa hủy diệt kinh hoàng, gây sát thương ma thuật\n[Hỏa] bỏ qua toàn bộ Phòng Thủ của kẻ địch. (Bộc Phá/Hỏa Cầu II)",
    102: "Bụi Kim Cương",
    103: "Đông cứng không gian xung quanh, gây sát thương ma thuật\n[Thủy] và đóng băng mọi kẻ địch. (Băng Kích II/Băng Thương)",
    104: "Thiểm Quang Kích",
    105: "Đâm thương với tốc độ ánh sáng, gây sát thương vật lý\n[Quang] với 100% tỉ lệ chí mạng. (Xuyên Tâm/Lôi Điệp)",
    106: "Sáng Suốt",
    107: "Thanh lọc tâm trí, tăng gấp đôi lượng MP hồi phục và tăng\ntốc độ ATB cho toàn đội. (Tĩnh Tâm/Ma Nguyên)",
    108: "Lốc Xoáy Hủy Diệt",
    109: "Cuộn xoáy bão tố xé toạc kẻ địch, gây sát thương vật lý\n[Vô hệ] lên toàn bộ chiến trường. (Cuồng Phong/Phong Trảm)",
    110: "Bất Diệt Kiên Trì",
    111: "Miễn nhiễm mọi sát thương trong 1 lượt và hồi phục 50% HP\ncho toàn bộ đồng minh. (Kiên Cường/Phòng Thủ Bất Bại)",
    112: "Long Ma Kiếm",
    113: "Chém ra hình bóng thần long, gây sát thương đặc biệt\n[Hắc Ám/6 đòn] lên kẻ địch gần mục tiêu. (Long Hồn/Khởi Nguyên)",
    114: "Băng Hỏa Bộc Phá",
    115: "Hòa quyện Lửa và Băng tạo vụ nổ đối cực, gây sát thương đặc biệt\n[Hỏa+Thủy] cực lớn lên toàn bộ kẻ địch. (Hỏa Cầu II/Băng Kích II)",
    116: "Huyết Ma",
    117: "Hút cạn sinh lực kẻ địch, gây sát thương ma thuật [Hắc Ám]\nvà chia đều lượng máu hút được cho toàn đội. (Hấp Thu/Hút Máu)",
    118: "Khoan Phá Kích",
    119: "Xoáy mũi thương xuyên thủng giáp địch, gây sát thương vật lý\n[Vô hệ] bỏ qua 100% Phòng Thủ. (Hoàng Gia Thương/Toái Thương Kích)",
    120: "Núi Lửa",
    121: "Đánh thức núi lửa phun trào dung nham, gây sát thương ma thuật\n[Hỏa] liên tục lên toàn bộ kẻ địch. (Nham Thạch/Nham Thạch)",
    122: "Kỳ Tích Lội Ngược",
    123: "Khi toàn đội sắp bị tiêu diệt, hồi sinh tất cả và hồi đầy\n100% HP/MP cùng thanh ATB. (Hồi Sinh/Diệt Vong)",
    124: "Hắc Hỏa Pháo",
    125: "Bắn chùm pháo hắc ám rực cháy, gây sát thương ma thuật\n[Hỏa+Hắc Ám] lên toàn bộ kẻ địch. (Hắc Thể/Bộc Phá)",
    126: "Thần Tốc",
    127: "Tăng tốc độ ATB của toàn đội lên mức tối đa ngay lập tức. (Tăng Tốc/Tăng Tốc)",
    128: "Thánh Nộ Phán Quyết",
    129: "Trời giáng sấm sét thánh thần trừng phạt, gây sát thương ma thuật\n[Quang] cực lớn lên toàn bộ kẻ địch. (Lôi Điệp II/Thánh Lực)",
    130: "Hắc Nguyệt",
    131: "Mặt trăng đen nuốt trọn ánh sáng, gây sát thương ma thuật\n[Hắc Ám] và giảm toàn bộ chỉ số của kẻ địch. (Hắc Vụ/Hố Đen)",
}
for r, text in two_coop.items():
    ws2.cell(r, 3).value = text

# =========================================================================
# ThreePlayerCoopSkillDataMessag (70 skills)
# =========================================================================
ws3 = wb["ThreePlayerCoopSkillDataMessag"]
three_coop = {
    6: "Thánh Giá Thần Long",
    7: "Gây sát thương đặc biệt [Quang+Hắc Ám/8 đòn] lên kẻ địch gần mục tiêu,\nbỏ qua mọi kháng nguyên tố. (Cuồng Phong/Tỏa Sáng/Xung Kích)",
    8: "Thiên Hà Lực",
    9: "Mở khóa sức mạnh vô tận của vũ trụ, gây sát thương đặc biệt\n[Vô hệ] lên toàn bộ kẻ địch. (Thiên Thạch/Trị Liệu/Tàng Hình)",
    10: "Tuyệt Kỹ Vô Song",
    11: "Ban Né Vật Lý và Phản Phép lên toàn đội. Đồng thời khiêu khích\nkẻ địch dồn đòn tấn công. (Bức Tường/Khiêu Khích/Phòng Thủ Bất Bại)",
    12: "Thiểm Quang Phù Du",
    13: "Gây sát thương đặc biệt [Quang] lên toàn bộ kẻ địch, đồng thời niệm\nHồi Phục liên tục cho toàn đội. (Hào Quang/Giả Chết/Âm Vang)",
    14: "Giải Phóng Tối Thượng",
    15: "Gây sát thương đặc biệt [Quang+Hắc Ám] lên kẻ địch gần mục tiêu.\nUy lực tăng theo các bùa lợi đang kích hoạt. (Ma Nguyên/Khích Lệ/Đại Dịch)",
    16: "Đại Bùng Nổ Big Bang",
    17: "Tạo vụ nổ với sức mạnh khai sinh vũ trụ, gây sát thương đặc biệt\n[Vô hệ/4 đòn] lên toàn bộ kẻ địch. (Hồi Sinh/Trọng Lực/Kích Hoạt Ma Lực)",
    18: "Khoảnh Khắc Thời Gian",
    19: "Gây sát thương đặc biệt [Vô hệ/3 đòn] lên một kẻ địch, và làm đầy\nthanh SP của toàn đội ngay lập tức. (Giác Ngộ/Hoàn Bích Kích/Bộc Phát)",
    20: "Trảm Kích Vĩnh Cửu",
    21: "Tung vô số đòn đánh trong một tích tắc, gây sát thương vật lý\n[Vô hệ/8 đòn] lên kẻ địch gần mục tiêu. (Quang Mang/Ngưng Đọng/Cuồng Nộ)",
    22: "Thiên Thể Bất Động",
    23: "Gây sát thương đặc biệt [Vô hệ] lên toàn bộ kẻ địch, và gây Ngưng Đọng.\nĐồng thời tăng tốc độ ATB của toàn đội. (Tăng Tốc/Vạn Vật/Ảnh Tung)",
    24: "Khải Huyền",
    25: "Gây sát thương đặc biệt [Vô hệ] lên toàn bộ kẻ địch, và tăng mạnh\nTấn Công cùng Phòng Thủ của toàn đội. (Chiến Hống/Kiên Cường/Luyện Kim Bại Hoại)",
    26: "Thần Mặt Trời Hyperion",
    27: "Gây sát thương đặc biệt [Vô hệ] lên kẻ địch gần mục tiêu.\nHP/MP càng cao, sát thương càng khủng khiếp. (Trảm Kích/Cuồng Phong Đao/Phi Thân)",
    28: "Hắc Thạch Trảo",
    29: "Gây sát thương đặc biệt [Hắc Ám/3 đòn] lên kẻ địch gần mục tiêu.\nCó thể gây Hóa Đá và giảm chỉ số địch. (Kiếm Khí/Thạch Trảm/Hố Đen)",
    30: "Mưa Sao Băng",
    31: "Bão sao băng rực cháy trút xuống, gây sát thương ma thuật\n[Hỏa+Quang] lên toàn bộ kẻ địch. (Thiên Thạch/Hỏa Cầu II/Lôi Điệp II)",
    32: "Kích Bộc",
    33: "Kích nổ toàn bộ ma lực tích tụ, gây sát thương đặc biệt\n[Hỏa/6 đòn] lên toàn bộ kẻ địch. (Tia Lửa/Bộc Phá/Hư Vô)",
    34: "Tia Sáng Long Thần",
    35: "Phóng chùm tia sáng long thần xé toạc không gian, gây sát thương\nđặc biệt [Quang+Hắc Ám] lên toàn bộ kẻ địch. (Khởi Nguyên/Tỏa Sáng/Long Hồn)",
    36: "Phượng Hoàng Thăng Thiên",
    37: "Triệu hồi phượng hoàng lửa hồi sinh toàn đội, hồi đầy HP/MP\nvà thiêu rụi kẻ địch bằng lửa thánh. (Hồi Sinh II/Hỏa Cầu II/Tận Thế Rồng)",
    38: "Lá Thư Cuối Cùng",
    39: "Giải phóng đòn đánh tuyệt mệnh, gây sát thương vật lý\n[Vô hệ] cực đại lên một mục tiêu. (Trảm Kích/Hoàn Bích Kích/Ngục Hỏa)",
    40: "Nhan Sắc Gaia",
    41: "Hồi phục toàn bộ HP, MP, xóa mọi trạng thái xấu và tăng tối đa\nmọi chỉ số cho toàn bộ đồng minh. (Cầu Nguyện/Luân Xa/Vạn Vật)",
    42: "Tinh Tú Bộc Phá",
    43: "Tạo vụ nổ tinh vân rực rỡ, gây sát thương đặc biệt\n[Quang] cực lớn lên toàn bộ kẻ địch. (Thánh Lực/Băng Tinh Trảm/Quang Mang)",
    44: "Phân Rã Vật Chất",
    45: "Phân rã liên kết nguyên tử của kẻ địch, gây sát thương ma thuật\n[Vô hệ] bỏ qua toàn bộ Phòng Thủ. (Chấn Động/Luyện Kim Bại Hoại/Hắc Thể)",
    46: "Thiên Lôi Giáng Lâm",
    47: "Triệu hồi cuồng lôi hủy diệt, gây sát thương ma thuật\n[Quang/8 đòn] lên toàn bộ kẻ địch. (Lôi Điệp II/Sấm Sét/Bão Từ Trường)",
    48: "Hồng Thủy Phát Quang",
    49: "Cuộn sóng ánh sáng thần thánh càn quét toàn bộ chiến trường,\ngây sát thương ma thuật [Quang+Thủy]. (Thánh Quang/Băng Kích II/Hào Quang)",
    50: "Tam Giác Lực Delta",
    51: "Kết hợp 3 nguồn ma lực tạo tam giác hủy diệt, gây sát thương\nma thuật [Đa hệ] cực lớn lên toàn bộ kẻ địch. (Hỏa Cầu II/Băng Kích II/Lôi Điệp II)",
    52: "Hỏa Diễm Omega",
    53: "Giải phóng ngọn lửa tối thượng của vũ trụ, thiêu rụi mọi kẻ địch\nvới lượng sát thương không thể cản phá. (Bộc Phá/Tỏa Sáng/Thiên Thạch)",
    54: "Bụi Ma Pháp",
    55: "Rải bụi ma thuật hồi phục MP liên tục và tăng tốc độ niệm phép\ncho toàn bộ đồng minh. (Ma Nguyên/Tĩnh Tâm/Cầu Nguyện)",
    56: "Đại Co Rút Big Crunch",
    57: "Co rút toàn bộ không gian rồi phát nổ, gây sát thương đặc biệt\n[Thời Gian] lên toàn bộ kẻ địch. (Trọng Lực/Hố Đen/Thiên Thạch)",
    58: "Người Tuyết Đè Bẹp",
    59: "Ném người tuyết khổng lồ đè bẹp toàn bộ kẻ địch, gây sát thương\nvật lý [Thủy] và đóng băng chúng. (Oa Phách/Băng Kích II/Sống Đao Trảm)",
    60: "Sám Hối",
    61: "Kẻ địch phải sám hối tội lỗi, nhận sát thương ma thuật [Quang]\ntỉ lệ thuận với sát thương chúng đã gây ra. (Thánh Lực/Phản Kháng/Diệt Vong)",
    62: "Hào Quang Lăng Kính",
    63: "Tán xạ ánh sáng bảy màu tăng cường toàn diện mọi thuộc tính\nvà miễn nhiễm sát thương nguyên tố cho toàn đội. (Thánh Quang/Hộ Giáp/Bảo Vệ)",
    64: "Đọa Đày",
    65: "Kéo kẻ địch vào cõi vĩnh hằng u tối, gây sát thương ma thuật\n[Hắc Ám] và có tỉ lệ tiêu diệt tức thì. (Ngục Hỏa/Hố Đen/Diệt Vong)",
    66: "Giao Hưởng Tuyết Rơi",
    67: "Tấu lên khúc giao hưởng băng tuyết xoa dịu đồng minh và đóng băng\ntoàn bộ kẻ thù trên chiến trường. (Băng Kích II/Trị Liệu II/Tĩnh Tâm)",
    68: "Khải Huyền Kiếm",
    69: "Thanh kiếm thức tỉnh chém rách màn đêm, gây sát thương vật lý\n[Quang] cực đại lên kẻ địch. (Trảm Kích/Thánh Quang/Toái Thương Kích)",
    70: "Hồng Liên Hỏa",
    71: "Ngọn lửa hoa sen đỏ rực thiêu đốt kẻ địch, gây sát thương ma thuật\n[Hỏa/4 đòn] liên tục. (Hỏa Cầu II/Nham Thạch/Bộc Phá)",
    72: "Thịnh Nộ Địa Cầu",
    73: "Mặt đất rung chuyển dữ dội, đá nhọn trồi lên đâm xuyên kẻ địch,\ngây sát thương vật lý [Vô hệ] cực lớn. (Nham Thạch/Cuồng Phong Đao/Phá Địa Trảm)",
    74: "Chuyển Động Omega",
    75: "Kích hoạt toàn bộ năng lượng của 3 chiến binh, tung chuỗi combo\n12 đòn liên hoàn càn quét chiến trường. (Khởi Nguyên/Siêu Việt/Vạn Vật)",
    76: "Đòn Kết Liễu",
    77: "Đòn đánh quyết định kết liễu kẻ thù đang suy yếu, gây sát thương\nvật lý [Vô hệ] tăng gấp 3 khi máu địch dưới 30%. (Trảm Kích/Xuyên Tâm/Tập Kích)",
    78: "Vạn Vật Hợp Nhất",
    79: "Hợp nhất sức mạnh của vũ trụ, gây sát thương đặc biệt [Vô hệ]\nbỏ qua toàn bộ phòng thủ và kháng phép. (Khởi Nguyên/Tỏa Sáng/Vạn Vật)",
    80: "Hào Quang Toàn Năng",
    81: "Bao bọc toàn đội trong hào quang hộ mệnh, hồi đầy máu và miễn nhiễm\nmọi sát thương trong 1 lượt. (Hào Quang/Cầu Nguyện/Bảo Vệ)",
    82: "Diễu Hành Thoảng Qua",
    83: "Tung ra ảo ảnh diễu hành làm hoa mắt kẻ thù, gây sát thương\nvật lý [Vô hệ] và giảm toàn bộ chỉ số của chúng. (Ảo Ảnh/Giả Chết/Ảnh Tung)",
    84: "Bùng Nổ Năng Lượng",
    85: "Giải phóng toàn bộ MP tích tụ thành vụ nổ năng lượng thuần khiết,\ngây sát thương ma thuật [Vô hệ] diện rộng. (Ma Nguyên/Kích Hoạt Ma Lực/Chấn Động)",
    86: "Lạm Phát Vũ Trụ",
    87: "Kéo giãn không gian vũ trụ, gây sát thương đặc biệt [Thời Gian]\nlên toàn bộ kẻ địch và làm đầy thanh ATB toàn đội. (Ngưng Đọng/Tăng Tốc/Vĩnh Cửu)",
    88: "Tiếng Vọng Vĩnh Hằng",
    89: "Những tiếng vọng từ cõi vĩnh hằng hồi phục toàn bộ trạng thái\ncho đồng minh và gây sát thương ma thuật lên địch. (Âm Vang/Hồi Sinh II/Cầu Nguyện)",
    90: "Vô Cực Kích",
    91: "Tung vô số đòn đánh không giới hạn, gây sát thương vật lý\n[Vô hệ/16 đòn] lên kẻ địch gần mục tiêu. (Cuồng Loạn/Xoáy Tử Thần/Trảm Kích)",
    92: "Thiên Bình Cân Bằng",
    93: "Cân bằng lại cán cân sinh mệnh, chuyển đổi sát thương đã nhận\nthành sức mạnh hủy diệt giáng xuống kẻ thù. (Phản Kháng/Tận Thế Rồng/Sám Hối)",
    94: "Ngày Tận Thế Armageddon",
    95: "Triệu hồi thảm họa tận thế hủy diệt toàn bộ chiến trường,\ngây sát thương đặc biệt [Đa hệ] tối thượng. (Khởi Nguyên/Thiên Thạch/Diệt Vong)",
    96: "Bão Không Kích",
    97: "Lao xuống từ không trung tạo cơn lốc xoáy chém nát kẻ địch,\ngây sát thương vật lý [Vô hệ] diện rộng. (Không Kích/Phi Thân/Cuồng Phong)",
    98: "Cầu Trảm",
    99: "Chém xoay tròn hình cầu tạo luồng kiếm khí bao trùm mọi hướng,\ngây sát thương vật lý [Vô hệ]. (Cuồng Phong Đao/Luân Vũ Trảm/Xoáy Tử Thần)",
    100: "Mưa Tinh Tú",
    101: "Mưa tinh tú ánh sáng giáng xuống như thác đổ, gây sát thương\nma thuật [Quang] liên tục lên toàn bộ kẻ địch. (Thánh Quang/Lôi Điệp II/Thiên Thạch)",
    102: "Phun Trào",
    103: "Dung nham phun trào từ lòng đất, thiêu đốt và hất tung toàn bộ\nkẻ thù lên không trung. (Nham Thạch/Hỏa Cầu II/Hỏa Sơn Trảm)",
    104: "Gió Cao Highwind",
    105: "Cơn cuồng phong bão táp quét sạch chiến trường, gây sát thương\nvật lý [Vô hệ] và đẩy lùi toàn bộ kẻ địch. (Phong Trảm/Cuồng Phong/Phi Thân)",
    106: "Phượng Hoàng Tung Cánh",
    107: "Đôi cánh phượng hoàng lửa rực cháy ban phước cho toàn đội và\nthiêu rụi kẻ địch bằng ngọn lửa vĩnh cửu. (Hồi Sinh II/Hỏa Cầu II/Khích Lệ)",
    108: "Khúc Hát Thiên Nga",
    109: "Khúc ca tráng lệ cuối cùng hồi phục toàn bộ đồng minh và tăng\ngấp đôi sát thương trong lượt tiếp theo. (Cầu Nguyện/Tĩnh Tâm/Khích Lệ)",
    110: "Vinh Quang Gaia",
    111: "Sức mạnh đất mẹ ban phúc lành hồi phục toàn diện và tăng mạnh\nkhả năng phòng thủ cho toàn đội. (Cầu Nguyện/Hộ Giáp/Bảo Vệ)",
    112: "Phá Vỡ Vật Chất",
    113: "Đập vỡ cấu trúc không gian và vật chất, gây sát thương đặc biệt\n[Hắc Ám] bỏ qua toàn bộ kháng cự. (Hư Vô/Hắc Thể/Hố Đen)",
    114: "Đại Hồng Thủy",
    115: "Cơn đại hồng thủy nhấn chìm toàn bộ kẻ địch, gây sát thương\nma thuật [Thủy] cực lớn. (Băng Kích II/Băng Tinh Trảm/Sóng Băng Giá)",
    116: "Lôi Xoáy",
    117: "Xoáy điện ma thuật giật liên hồi, gây sát thương ma thuật\n[Quang/6 đòn] và làm tê liệt toàn bộ kẻ thù. (Lôi Điệp II/Chấn Động/Bão Từ Trường)",
    118: "Tia Sáng Tàn Sát",
    119: "Phóng chùm tia năng lượng hủy diệt xuyên thủng mọi hàng phòng ngự,\ngây sát thương đặc biệt [Hắc Ám]. (Long Hồn/Hắc Khế/Hắc Thể)",
    120: "Tam Giác Thần Thánh Trine",
    121: "Kết ấn tam giác thần thánh phong ấn và tiêu diệt kẻ thù bằng\nsát thương ma thuật [Quang] tối thượng. (Thánh Quang/Lôi Điệp II/Tỏa Sáng)",
    122: "Tia Gamma Bùng Nổ",
    123: "Vụ nổ tia gamma vũ trụ hủy diệt mọi sinh linh trên chiến trường,\ngây sát thương đặc biệt [Quang+Hắc Ám]. (Siêu Tân Tinh/Hắc Thể/Thiên Thạch)",
    124: "Thần Thương Brionac",
    125: "Phóng ngọn thánh thương huyền thoại đâm xuyên mục tiêu,\ngây sát thương vật lý [Quang] với 100% chí mạng. (Hoàng Gia Thương/Thánh Quang/Xuyên Tâm)",
    126: "Sụp Đổ Trọng Lực",
    127: "Trọng lực sụp đổ nghiền nát kẻ thù thành cát bụi, gây sát thương\nma thuật [Thời Gian] cực lớn. (Trọng Lực/Hố Đen/Đại Co Rút)",
    128: "Hình Nhân Ảo Ảnh",
    129: "Tạo hàng loạt hình nhân ảo ảnh đánh lạc hướng và phản công\nmọi đòn tấn công của kẻ thù. (Ảo Ảnh/Ảnh Tung/Giả Chết)",
    130: "Chuộc Tội",
    131: "Thanh tẩy mọi tội lỗi, hồi sinh đồng minh và trút bỏ toàn bộ\nsát thương ngược lại lên đầu kẻ địch. (Hồi Sinh II/Sám Hối/Thánh Lực)",
    132: "Biến Dạng Thời Gian",
    133: "Bẻ cong thời gian, giúp toàn đội nhận thêm 1 lượt hành động\nngay lập tức sau khi xuất chiêu. (Tăng Tốc/Ngưng Đọng/Hoàn Bích Kích)",
    134: "Tiếng Hú Địa Ngục",
    135: "Tiếng gầm từ cõi âm làm kinh hồn bạt vía quân địch, gây sợ hãi\nvà giảm 50% toàn bộ chỉ số của chúng. (Hắc Vụ/Khiêu Khích/Đoạt Hồn)",
    136: "Cuồng Tưởng Khúc Tuyết Rơi",
    137: "Tuyết trắng cuộn trào theo điệu cuồng tưởng, gây sát thương ma thuật\n[Thủy] và đóng băng vĩnh viễn kẻ địch. (Băng Kích II/Băng Thương/Tĩnh Tâm)",
    138: "Binh Pháp Nghệ Thuật",
    139: "Bày bố trận địa tác chiến hoàn hảo, tăng 100% tỉ lệ chí mạng và\n50% sức tấn công cho toàn đội. (Chiến Hống/Kỷ Luật/Khích Lệ)",
    140: "Xích Diễm Hỏa",
    141: "Ngọn lửa đỏ thẫm bốc cháy dữ dội thiêu rụi mọi chướng ngại vật,\ngây sát thương ma thuật [Hỏa] cực đại. (Hỏa Cầu II/Hồng Liên Hỏa/Bộc Phá)",
    142: "Thần Phẫn Gaia",
    143: "Cơn thịnh nộ của đất mẹ trừng phạt kẻ xúc phạm, gây sát thương\nvật lý [Vô hệ] và làm choáng toàn bộ kẻ thù. (Thịnh Nộ Địa Cầu/Nham Thạch/Cuồng Phong Đao)",
    144: "Xung Lực Alpha",
    145: "Cú va chạm khởi nguyên tạo sóng xung kích hủy diệt mọi vật chất,\ngây sát thương đặc biệt [Vô hệ] tối cao. (Khởi Nguyên/Xung Lực/Vạn Vật)",
}
for r, text in three_coop.items():
    ws3.cell(r, 3).value = text

wb.save(excel_path)
print("Updated all Two-Player and Three-Player Co-op skills successfully (266 entries)!")
